# Inventory Optimization

In [1]:
import pandas as pd

In [2]:
Auto = pd.read_csv('/Users/Stalwarts/Desktop/Personal/AI/ecommerce_dataset.csv', on_bad_lines='skip')

In [3]:
Auto.head()

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,...,campaign_source,device_type,traffic_source,session_duration_minutes,pages_visited,abandoned_cart_before,fraud_risk_score,profit_margin_percent,order_priority,support_ticket_created
0,ORD-XAJI0,2024-10-14 11:20:05.496679,2024,10,14,11,20,5,No,Completed,...,Email,Mobile,Search,52.1,13,No,45.3,28.66,Medium,Yes
1,ORD-NHJ7X,2024-10-21 00:49:44.681065,2024,10,21,0,49,44,No,Completed,...,Google Ads,Desktop,Referral,36.2,15,No,97.1,33.91,Low,Yes
2,ORD-YTJXE,2025-03-17 19:49:36.983317,2025,3,17,19,49,36,No,Completed,...,Facebook,Tablet,Search,43.1,13,No,43.8,52.77,High,No
3,ORD-EIMVI,2024-09-27 06:24:44.913768,2024,9,27,6,24,44,No,Completed,...,Instagram,Mobile,Direct,39.5,18,Yes,96.9,38.15,Low,Yes
4,ORD-OR56F,2025-05-21 17:10:48.401882,2025,5,21,17,10,48,No,Completed,...,Facebook,Tablet,Social,28.0,3,Yes,45.8,33.05,High,Yes

In [4]:
Auto.columns

Index(['order_id', 'order_date', 'order_year', 'order_month', 'order_day',
       'order_hour', 'order_minute', 'order_second', 'is_weekend',
       'order_status', 'return_reason', 'customer_id', 'customer_name',
       'gender', 'age', 'customer_segment', 'country', 'city',
       'customer_loyalty_score', 'total_orders_by_customer',
       'account_creation_date', 'product_id', 'product_name', 'category',
       'sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
       'stock_quantity', 'unit_price_usd', 'quantity', 'discount_percent',
       'discount_amount_usd', 'total_price_usd', 'cost_usd', 'profit_usd',
       'tax_usd', 'currency', 'payment_method', 'payment_status',
       'installment_plan', 'shipping_method', 'shipping_cost_usd',
       'delivery_days', 'shipping_country', 'warehouse_location',
       'delivery_status', 'rating', 'review_sentiment', 'customer_feedback',
       'coupon_used', 'coupon_code', 'campaign_source', 'device_type',
       'traffic_source', 'session_duration_minutes', 'pages_visited',
       'abandoned_cart_before', 'fraud_risk_score', 'profit_margin_percent',
       'order_priority', 'support_ticket_created'],
      dtype='object')

### 1. Stock-out Prediction

In [5]:
import duckdb
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.linear_model import PoissonRegressor
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (mean_absolute_error,classification_report,confusion_matrix)

In [6]:
con = duckdb.connect("inventory.duckdb", read_only = True)

df = con.execute("""
SELECT *
FROM read_csv_auto('/Users/Stalwarts/Desktop/Personal/AI/ecommerce_dataset.csv')
""").df()
con.close()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [7]:
query = """
SELECT
    product_id,
    product_name,
    order_date,

    category,
    sub_category,
    brand,

    AVG(unit_price_usd) AS avg_price,
    AVG(discount_percent) AS avg_discount,

    SUM(quantity) AS daily_demand,

    AVG(stock_quantity) AS avg_stock,

    AVG(product_rating_avg) AS avg_rating,

    COUNT(DISTINCT order_id) AS num_orders,

    MAX(is_weekend) AS is_weekend

FROM df

GROUP BY
    product_id,
    product_name,
    order_date,
    category,
    sub_category,
    brand
"""

daily_df = duckdb.query(query).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [8]:
print(daily_df)

        product_id            product_name                 order_date  \
0         PRD-FSRL  Coffee Maker Automatic 2025-07-06 03:35:47.472580
1         PRD-LD2J        Swimming Goggles 2024-05-14 02:49:55.022824
2         PRD-27WX          USB Hub 7-Port 2024-02-11 10:56:12.441825
3         PRD-I6EN     LED Strip Lights 5m 2024-06-25 04:47:50.466358
4         PRD-SAUM          USB Hub 7-Port 2025-08-03 15:34:41.535573
...            ...                     ...                        ...
1000118   PRD-UPI7    Resistance Bands Set 2025-06-17 10:49:30.027806
1000119   PRD-Z3SG    Denim Jeans Slim Fit 2025-01-02 11:42:16.679002
1000120   PRD-ZR1L           Exercise Ball 2025-10-17 21:31:10.831655
1000121   PRD-MKJU          USB Hub 7-Port 2025-08-07 19:11:22.187411
1000122   PRD-YML2    Resistance Bands Set 2024-07-27 15:48:16.443955

            category     sub_category     brand  avg_price  avg_discount  \
0               Home          Kitchen     GoPro     252.36          15.0
1             Sports          Outdoor   Philips     247.83          15.0
2        Electronics          Laptops    Baseus     287.72          10.0
3               Home        Furniture  Logitech      54.43          25.0
4        Electronics          Cameras    Adidas     160.57          10.0
...              ...              ...       ...        ...           ...
1000118       Health      Supplements    Xiaomi      34.28          20.0
1000119     Clothing      Accessories  Logitech     108.52           5.0
1000120       Sports      Sports Wear    Fitbit      22.04           5.0
1000121  Electronics          Tablets       JBL     407.12          10.0
1000122       Health  Medical Devices  Logitech     164.57           0.0

         daily_demand  avg_stock  avg_rating  num_orders  is_weekend
0                 1.0      969.0         3.6           1        True
1                 5.0      401.0         4.0           1       False
2                 1.0      258.0         3.0           1        True
3                 2.0      378.0         4.1           1       False
4                 5.0      890.0         3.7           1        True
...               ...        ...         ...         ...         ...
1000118           3.0      442.0         4.8           1       False
1000119           2.0      867.0         3.2           1       False
1000120           2.0      554.0         3.1           1       False
1000121           1.0      924.0         3.7           1       False
1000122           5.0      470.0         4.3           1        True

[1000123 rows x 13 columns]

In [9]:
daily_df = daily_df.sort_values(
    ['product_id', 'order_date']
)

# Lag Features
daily_df['lag_1'] = (
    daily_df.groupby('product_id')['daily_demand']
    .shift(1)
)

daily_df['lag_7'] = (
    daily_df.groupby('product_id')['daily_demand']
    .shift(7)
)

# Rolling Features
daily_df['rolling_avg_7'] = (
    daily_df.groupby('product_id')['daily_demand']
    .transform(
        lambda x: x.rolling(
            window=7,
            min_periods=1
        ).mean()
    )
)

daily_df['rolling_avg_30'] = (
    daily_df.groupby('product_id')['daily_demand']
    .transform(
        lambda x: x.rolling(
            window=30,
            min_periods=1
        ).mean()
    )
)

In [10]:
daily_df['lag_1'] = daily_df['lag_1'].fillna(0)

daily_df['lag_7'] = daily_df['lag_7'].fillna(
    daily_df['rolling_avg_7']
)

daily_df['rolling_avg_7'] = (
    daily_df['rolling_avg_7']
    .fillna(daily_df['daily_demand'])
)

daily_df['rolling_avg_30'] = (
    daily_df['rolling_avg_30']
    .fillna(daily_df['rolling_avg_7'])
)

# Calendar Features
daily_df['month'] = daily_df['order_date'].dt.month
daily_df['day_of_week'] = daily_df['order_date'].dt.dayofweek

In [11]:
daily_df['stock_out'] = np.where(
    daily_df['avg_stock'] <= 2,
    1,
    0
)

In [12]:
features = [
    'avg_price',
    'avg_discount',
    'avg_rating',
    'num_orders',
    'avg_stock',

    'lag_1',
    'lag_7',
    'rolling_avg_7',
    'rolling_avg_30',

    'month',
    'day_of_week',

    'category',
    'sub_category',
    'product_name',
    'brand',
    'is_weekend'
]

In [13]:
print(daily_df.columns.tolist())

['product_id', 'product_name', 'order_date', 'category', 'sub_category', 'brand', 'avg_price', 'avg_discount', 'daily_demand', 'avg_stock', 'avg_rating', 'num_orders', 'is_weekend', 'lag_1', 'lag_7', 'rolling_avg_7', 'rolling_avg_30', 'month', 'day_of_week', 'stock_out']

In [14]:
X = daily_df[features]

y_demand = daily_df['daily_demand']

In [15]:
numeric_features = [
    'avg_price',
    'avg_discount',
    'avg_rating',
    'num_orders',
    'avg_stock',
    'lag_1',
    'lag_7',
    'rolling_avg_7',
    'rolling_avg_30',
    'month',
    'day_of_week'
]

categorical_features = [
    'category',
    'sub_category',
    'product_name',
    'brand',
    'is_weekend'
]

In [16]:
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

#### Demand Forecasting Model

In [17]:
demand_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', PoissonRegressor(alpha=0.1, max_iter=500))
])

In [18]:
train_df = daily_df[daily_df['order_date'] < '2025-01-01']
test_df = daily_df[daily_df['order_date'] >= '2025-01-01']

X_train = train_df[features]
X_test = test_df[features]

y_train_demand = train_df['daily_demand']
y_test_demand = test_df['daily_demand']

In [19]:
demand_model.fit(X_train, y_train_demand)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['avg_price', 'avg_discount',
                                                   'avg_rating', 'num_orders',
                                                   'avg_stock', 'lag_1',
                                                   'lag_7', 'rolling_avg_7',
                                                   'rolling_avg_30', 'month',
                                                   'day_of_week']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['category', 'sub_category',
                                                   'product_name', 'brand',
                                                   'is_weekend'])])),
                ('regressor', PoissonRegressor(alpha=0.1, max_iter=500))])

In [20]:
demand_predictions = demand_model.predict(X_test)

print(
    "Demand MAE:",
    mean_absolute_error(y_test_demand, demand_predictions)
)

Demand MAE: 0.4696676230741604

In [21]:
forecast_df = test_df.copy()

forecast_df['predicted_demand'] = np.round(
    demand_predictions,
    2
)

In [22]:
forecast_df['days_until_stockout'] = np.where(
    forecast_df['predicted_demand'] > 0,

    forecast_df['avg_stock'] /
    forecast_df['predicted_demand'],

    np.nan
)

In [23]:
forecast_df['demand_stddev'] = (
    forecast_df.groupby('product_id')['daily_demand']
    .transform(
        lambda x: x.rolling(
            window=30,
            min_periods=1
        ).std()
    )
)

forecast_df['demand_stddev'] = (
    forecast_df['demand_stddev']
    .fillna(0)
)

In [24]:
Z_SCORE = 1.65

LEAD_TIME_DAYS = 7

forecast_df['safety_stock'] = (
    Z_SCORE *
    forecast_df['demand_stddev'] *
    np.sqrt(LEAD_TIME_DAYS)
)

In [25]:
final_forecast_df = forecast_df[[
    'order_date',

    'product_id',
    'product_name',
    'category',
    'sub_category',
    'brand',

    'avg_stock',

    'daily_demand',
    'predicted_demand',

    'safety_stock',

    'avg_price',
    'avg_discount',

    'rolling_avg_7',
    'rolling_avg_30'
]]

In [26]:
final_forecast_df = final_forecast_df.rename(columns={

    'avg_stock': 'current_stock',

    'daily_demand': 'actual_demand',

    'avg_price': 'unit_price',

    'avg_discount': 'discount_percent'
})

In [27]:
final_forecast_df.head(20)

,order_date,product_id,product_name,category,sub_category,brand,current_stock,actual_demand,predicted_demand,safety_stock,unit_price,discount_percent,rolling_avg_7,rolling_avg_30
973472,2025-01-04 11:19:07.731609,PRD-0000,Water Bottle Insulated,Sports,Sports Wear,JBL,646.0,2.0,2.51,0.000000,248.92,0.0,3.000000,3.000000
897252,2025-08-22 19:33:28.471487,PRD-0000,USB-C Fast Charger 65W,Electronics,Accessories,Adidas,894.0,3.0,2.63,3.086867,285.29,0.0,3.000000,3.000000
441869,2025-09-30 20:59:56.515064,PRD-0001,Hooded Sweatshirt,Clothing,Shoes,Huawei,74.0,5.0,5.41,0.000000,19.86,5.0,5.000000,5.000000
538737,2025-04-08 14:10:43.246409,PRD-0003,Storage Box Set,Home,Decor,Adidas,737.0,2.0,1.90,0.000000,38.85,5.0,2.000000,2.000000
307736,2025-04-02 07:09:37.397213,PRD-0008,Foam Roller,Health,Supplements,Lenovo,962.0,1.0,1.97,0.000000,145.11,10.0,2.333333,2.333333
760659,2025-09-19 07:49:17.123309,PRD-0009,Swimming Goggles,Sports,Outdoor,Apple,11.0,5.0,2.68,0.000000,230.47,0.0,3.000000,3.000000
162403,2025-09-11 11:07:57.130136,PRD-000D,Jump Rope Speed,Sports,Sports Wear,JBL,222.0,2.0,1.87,0.000000,146.57,5.0,2.000000,2.000000
562661,2025-10-11 14:15:43.005182,PRD-000E,Casual Sneakers,Clothing,Mens Wear,Dell,525.0,4.0,3.84,0.000000,42.74,0.0,4.000000,4.000000
464641,2025-12-25 22:12:37.170449,PRD-000F,Desk Lamp LED,Home,Furniture,Adidas,147.0,3.0,3.05,0.000000,33.09,10.0,3.500000,3.500000
443845,2026-01-24 09:38:02.987364,PRD-000F,Fitness Smart Band,Health,Fitness,Nikon,133.0,1.0,2.27,6.173735,36.32,10.0,2.666667,2.666667
262110,2025-06-14 09:00:00.648438,PRD-000H,Running Shoes Air Zoom,Clothing,Mens Wear,Adidas,598.0,3.0,2.70,0.000000,149.83,0.0,3.000000,3.000000
664419,2025-05-05 14:18:07.761949,PRD-000K,Vacuum Robot Cleaner,Home,Appliances,Sony,461.0,4.0,3.05,0.000000,143.44,10.0,3.500000,3.500000
282143,2025-06-02 12:37:55.828133,PRD-000Y,Blender 1000W,Home,Decor,Philips,283.0,2.0,1.91,0.000000,150.89,0.0,2.000000,2.000000
559641,2025-09-10 02:40:08.402666,PRD-000Y,Treadmill Folding,Sports,Gym Equipment,Philips,449.0,1.0,1.57,3.086867,181.00,5.0,1.500000,1.500000
288906,2025-12-05 02:40:08.591012,PRD-000Y,Badminton Racket,Sports,Outdoor,JBL,603.0,4.0,2.14,6.668396,247.33,10.0,2.333333,2.333333
142764,2025-11-10 10:03:09.426608,PRD-0016,Power Bank 20000mAh,Electronics,Accessories,Huawei,648.0,2.0,1.94,0.000000,251.03,15.0,2.000000,2.000000
935222,2025-03-12 02:04:40.046478,PRD-0018,Screen Protector Tempered Glass,Electronics,Accessories,Xiaomi,752.0,3.0,2.68,0.000000,275.56,10.0,3.000000,3.000000
948042,2025-09-30 12:21:36.307074,PRD-001B,Resistance Bands Set,Health,Fitness,Xiaomi,346.0,3.0,1.90,0.000000,173.53,10.0,2.000000,2.000000
543981,2025-07-26 23:15:59.767838,PRD-001C,Digital Thermometer,Health,Supplements,Fitbit,426.0,2.0,1.92,0.000000,12.66,10.0,2.000000,2.000000
806071,2025-01-20 15:55:17.875429,PRD-001D,USB Hub 7-Port,Electronics,Smartphones,Baseus,744.0,2.0,1.89,0.000000,355.53,25.0,2.000000,2.000000

#### Stock-out Prediction Model

In [28]:
stockout_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        random_state=42
    ))
])

In [29]:
y_train_stockout = train_df['stock_out']
y_test_stockout = test_df['stock_out']

stockout_model.fit(X_train, y_train_stockout)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['avg_price', 'avg_discount',
                                                   'avg_rating', 'num_orders',
                                                   'avg_stock', 'lag_1',
                                                   'lag_7', 'rolling_avg_7',
                                                   'rolling_avg_30', 'month',
                                                   'day_of_week']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['category', 'sub_category',
                                                   'product_name', 'brand',
                                                   'is_weekend'])])),
                ('classifier',
                 RandomForestClassifier(max_depth=10, random_state=42))])

In [30]:
stockout_predictions = stockout_model.predict(X_test)

In [31]:
print(classification_report(
    y_test_stockout,
    stockout_predictions
))

print(confusion_matrix(
    y_test_stockout,
    stockout_predictions
))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    543251
           1       1.00      1.00      1.00      1623

    accuracy                           1.00    544874
   macro avg       1.00      1.00      1.00    544874
weighted avg       1.00      1.00      1.00    544874

[[543251      0]
 [     0   1623]]

In [32]:
print(
    "Stockout MAE:",
    mean_absolute_error(y_test_stockout, stockout_predictions)
)

Stockout MAE: 0.0

In [33]:
stockout_probabilities = stockout_model.predict_proba(X_test)[:, 1]

In [34]:
forecast_df['stockout_probability'] = np.round(
    stockout_probabilities,
    3
)

In [35]:
forecast_df['days_until_stockout'] = np.where(
    forecast_df['predicted_demand'] > 0,

    forecast_df['avg_stock'] /
    forecast_df['predicted_demand'],

    np.nan
)

In [36]:
forecast_df['reorder_point'] = (
    forecast_df['predicted_demand']
    *
    LEAD_TIME_DAYS
) + forecast_df['safety_stock']

In [37]:
forecast_df['current_stock'] = (
    forecast_df['avg_stock']
)

In [38]:
forecast_df['reorder_quantity'] = np.where(

    forecast_df['current_stock']
    <
    forecast_df['reorder_point'],

    np.ceil(
        forecast_df['reorder_point']
        -
        forecast_df['current_stock']
    ),

    0
)

In [39]:
reorder_df = forecast_df[
    forecast_df['reorder_quantity'] > 0
]

In [40]:
print(
    reorder_df[[
        'product_id',
        'product_name',
        'current_stock',
        'predicted_demand',
        'safety_stock',
        'reorder_point',
        'reorder_quantity'
    ]].head(20)
)

       product_id                     product_name  current_stock  \
760659   PRD-0009                 Swimming Goggles           11.0
520690   PRD-001I              LED Strip Lights 5m           15.0
371764   PRD-006F                   USB Hub 7-Port            3.0
559127   PRD-0075                 Portable SSD 1TB           21.0
433087   PRD-0095                Treadmill Folding            0.0
33860    PRD-00AN           Sports Bra High Impact           18.0
842103   PRD-00C5           USB-C Fast Charger 65W            1.0
130440   PRD-00HJ   Digital Blood Pressure Monitor           14.0
258476   PRD-00KD                     Baseball Cap            1.0
505146   PRD-00KN  Screen Protector Tempered Glass           11.0
882249   PRD-00OY              Digital Thermometer           16.0
900899   PRD-00PD                    4K Webcam Pro           13.0
261134   PRD-00QS                    Desk Lamp LED           11.0
505903   PRD-00V2                Yoga Mat Non-Slip           27.0
907883   PRD-00Z2                   USB Hub 7-Port           13.0
967019   PRD-0118                  Jump Rope Speed           18.0
409748   PRD-015Q   Digital Blood Pressure Monitor           27.0
592535   PRD-01CA                    Desk Lamp LED            2.0
189308   PRD-01FL                       Gym Gloves            3.0
208024   PRD-01K8           Coffee Maker Automatic            0.0

        predicted_demand  safety_stock  reorder_point  reorder_quantity
760659              2.68      0.000000      18.760000               8.0
520690              2.61      0.000000      18.270000               4.0
371764              1.37      0.000000       9.590000               7.0
559127              5.31      0.000000      37.170000              17.0
433087              1.69      3.086867      14.916867              15.0
33860               5.42      0.000000      37.940000              20.0
842103              2.68      0.000000      18.760000              18.0
130440              2.69      0.000000      18.830000               5.0
258476              1.94      0.000000      13.580000              13.0
505146              4.98      0.000000      34.860000              24.0
882249              3.77      0.000000      26.390000              11.0
900899              1.93      0.000000      13.510000               1.0
261134              5.38      0.000000      37.660000              27.0
505903              3.86      0.000000      27.020000               1.0
907883              3.66      0.000000      25.620000              13.0
967019              2.70      0.000000      18.900000               1.0
409748              5.33      0.000000      37.310000              11.0
592535              5.42      0.000000      37.940000              36.0
189308              2.71      0.000000      18.970000              16.0
208024              5.34      0.000000      37.380000              38.0

In [41]:
final_forecast_df = forecast_df[[
    'order_date',

    'product_id',
    'product_name',
    'category',
    'sub_category',
    'brand',

    'avg_stock',

    'daily_demand',
    'predicted_demand',

    'avg_price',
    'avg_discount',

    'rolling_avg_7',
    'rolling_avg_30',

    'stockout_probability',

    'days_until_stockout',

    'safety_stock',
    'reorder_quantity',
]]

In [42]:
final_forecast_df = final_forecast_df.sort_values(
    by='stockout_probability',
    ascending=False
)

In [43]:
final_forecast_df.head(20)

,order_date,product_id,product_name,category,sub_category,brand,avg_stock,daily_demand,predicted_demand,avg_price,avg_discount,rolling_avg_7,rolling_avg_30,stockout_probability,days_until_stockout,safety_stock,reorder_quantity
349260,2025-09-06 22:37:14.161244,PRD-JWX7,Wireless Mouse 2.4GHz,Electronics,Smartphones,Samsung,0.0,4.0,3.83,53.02,5.0,4.000000,4.000000,0.791,0.000000,0.000000,27.0
438214,2025-01-26 19:21:15.174842,PRD-GOE7,Treadmill Folding,Sports,Outdoor,Adidas,1.0,5.0,5.33,163.16,5.0,5.000000,5.000000,0.781,0.187617,0.000000,37.0
24996,2025-06-01 04:15:10.923362,PRD-OIF8,USB-C Fast Charger 65W,Electronics,Smartphones,Samsung,0.0,5.0,4.25,491.85,0.0,4.500000,4.500000,0.771,0.000000,3.086867,33.0
580397,2025-10-25 06:41:01.502426,PRD-F1FA,Storage Box Set,Home,Kitchen,Anker,2.0,4.0,3.60,249.21,0.0,4.000000,4.000000,0.761,0.555556,0.000000,24.0
119758,2025-02-23 18:21:26.294055,PRD-2M47,Bedsheet Set Cotton,Home,Kitchen,GoPro,1.0,4.0,3.77,221.95,10.0,4.000000,4.000000,0.761,0.265252,0.000000,26.0
592535,2025-09-13 00:47:43.500684,PRD-01CA,Desk Lamp LED,Home,Bedding,Sony,2.0,5.0,5.42,215.73,0.0,5.000000,5.000000,0.761,0.369004,0.000000,36.0
701237,2025-09-28 18:40:10.099523,PRD-C4J9,Air Fryer 5L,Home,Furniture,Asus,1.0,5.0,5.41,211.65,5.0,5.000000,5.000000,0.760,0.184843,0.000000,37.0
836578,2025-01-25 21:04:14.697438,PRD-5ZM0,Coffee Maker Automatic,Home,Decor,Adidas,0.0,4.0,3.77,109.15,5.0,4.000000,4.000000,0.752,0.000000,0.000000,27.0
616372,2025-08-17 20:38:14.865668,PRD-IMWN,Massage Gun Deep Tissue,Health,Supplements,Huawei,1.0,5.0,3.65,17.80,5.0,4.000000,4.000000,0.751,0.273973,0.000000,25.0
87803,2025-11-22 19:29:22.190646,PRD-EE85,Vacuum Robot Cleaner,Home,Furniture,JBL,0.0,4.0,3.85,192.66,10.0,4.000000,4.000000,0.751,0.000000,0.000000,27.0
302331,2025-08-24 15:48:49.922752,PRD-95VZ,4K Webcam Pro,Electronics,Smartphones,Huawei,2.0,4.0,3.82,443.06,0.0,4.000000,4.000000,0.751,0.523560,0.000000,25.0
465504,2025-09-21 03:29:45.768819,PRD-WGLN,Bedsheet Set Cotton,Home,Kitchen,GoPro,0.0,5.0,4.27,236.69,10.0,4.500000,4.500000,0.750,0.000000,3.086867,33.0
483914,2025-04-05 03:25:25.668677,PRD-BS3S,Portable SSD 1TB,Electronics,Smartphones,Huawei,2.0,5.0,5.35,323.11,15.0,5.000000,5.000000,0.750,0.373832,0.000000,36.0
198348,2025-08-02 00:26:05.889782,PRD-EN1E,Swimming Goggles,Sports,Accessories,Dell,0.0,4.0,4.03,220.61,10.0,4.333333,4.333333,0.750,0.000000,0.000000,29.0
896397,2025-06-21 04:09:59.638247,PRD-2KSM,Badminton Racket,Sports,Sports Wear,Nike,0.0,5.0,5.38,182.25,5.0,5.000000,5.000000,0.750,0.000000,0.000000,38.0
357818,2025-05-11 08:41:17.351960,PRD-LJ7V,Vacuum Robot Cleaner,Home,Appliances,Dell,1.0,5.0,4.24,286.98,5.0,4.500000,4.500000,0.741,0.235849,3.086867,32.0
583877,2025-01-12 14:35:28.514002,PRD-5USE,Treadmill Folding,Sports,Sports Wear,Samsung,2.0,4.0,3.78,15.05,15.0,4.000000,4.000000,0.741,0.529101,0.000000,25.0
859007,2025-02-15 06:51:27.829903,PRD-E2A1,Badminton Racket,Sports,Accessories,Samsung,1.0,4.0,3.78,249.64,5.0,4.000000,4.000000,0.741,0.264550,0.000000,26.0
501777,2025-08-23 08:03:54.799537,PRD-J3YR,Digital Thermometer,Health,Personal Care,Lenovo,1.0,5.0,5.40,158.57,10.0,5.000000,5.000000,0.741,0.185185,0.000000,37.0
137041,2025-04-26 19:52:16.582092,PRD-QQE7,Dumbbells Set Adjustable,Sports,Gym Equipment,Xiaomi,2.0,5.0,5.36,75.21,10.0,5.000000,5.000000,0.741,0.373134,0.000000,36.0

In [44]:
len(final_forecast_df)

544874

In [45]:
final_forecast_df.to_csv(
    'inventory_forecast_output.csv',
    index=False
)