# Optimization

In [1]:
import pandas as pd

### Warehouse Management

In [2]:
WH_1 = pd.read_csv('warehouse_1.csv')

In [3]:
WH_1 = WH_1[['product_id', 'product_name', 'category','sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
'stock_quantity', 'unit_price_usd','shipping_method', 'shipping_cost_usd', 'delivery_days', 'shipping_country', 'warehouse_location',
                'rating']]

In [4]:
WH_1.columns

Index(['product_id', 'product_name', 'category', 'sub_category', 'brand',
       'product_rating_avg', 'product_reviews_count', 'stock_quantity',
       'unit_price_usd', 'shipping_method', 'shipping_cost_usd',
       'delivery_days', 'shipping_country', 'warehouse_location', 'rating'],
      dtype='object')

In [5]:
WH_1.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-1FPK,Coffee Maker Automatic,Home,Kitchen,Nike,3.2,3112,99,120.51,Economy,1.97,5,Netherlands,UK,3
1,PRD-C6UZ,Yoga Mat Non-Slip,Health,Supplements,Asus,3.8,3758,146,60.33,Next Day,5.48,3,United States,UK,1
2,PRD-T2TA,Blender 1000W,Home,Furniture,Asus,3.0,2973,899,295.89,Economy,20.40,13,France,UK,2
3,PRD-IROD,Badminton Racket,Sports,Accessories,Adidas,3.8,3825,884,186.33,Express,4.76,8,Italy,USA-West,3
4,PRD-LBR7,Screen Protector Tempered Glass,Electronics,Cameras,Anker,3.1,4160,82,427.16,Standard,15.48,7,Germany,UK,3

In [6]:
df_cleaned = WH_1.drop_duplicates(subset='product_id', keep='first')

In [7]:
WH_1 = df_cleaned.copy()

In [8]:
len(WH_1)

96951

In [9]:
WH_1.head(10)

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-1FPK,Coffee Maker Automatic,Home,Kitchen,Nike,3.2,3112,99,120.51,Economy,1.97,5,Netherlands,UK,3
1,PRD-C6UZ,Yoga Mat Non-Slip,Health,Supplements,Asus,3.8,3758,146,60.33,Next Day,5.48,3,United States,UK,1
2,PRD-T2TA,Blender 1000W,Home,Furniture,Asus,3.0,2973,899,295.89,Economy,20.40,13,France,UK,2
3,PRD-IROD,Badminton Racket,Sports,Accessories,Adidas,3.8,3825,884,186.33,Express,4.76,8,Italy,USA-West,3
4,PRD-LBR7,Screen Protector Tempered Glass,Electronics,Cameras,Anker,3.1,4160,82,427.16,Standard,15.48,7,Germany,UK,3
5,PRD-60FK,Coffee Maker Automatic,Home,Kitchen,Nike,3.4,2162,517,156.79,Express,15.93,5,France,USA-West,5
6,PRD-253J,Air Fryer 5L,Home,Appliances,Logitech,4.7,3855,227,75.88,Express,9.96,5,Canada,USA-East,3
7,PRD-LOOK,Electric Toothbrush,Home,Bedding,Baseus,3.8,3105,693,229.48,Next Day,5.25,13,Australia,UK,3
8,PRD-2H2Z,Phone Case Shockproof,Electronics,Smartphones,Samsung,4.1,994,467,75.34,Economy,22.43,12,Italy,Asia-Pacific,2
9,PRD-48P0,Storage Box Set,Home,Appliances,Nikon,4.8,3999,224,96.42,Economy,22.99,10,Belgium,UK,4

In [10]:
WH_1 = WH_1.copy()
for i in WH_1.index:
    # Use .loc to modify the DataFrame in place based on row index and column name
    if WH_1.loc[i, 'stock_quantity'] <= 0:
        WH_1.loc[i, 'stock_quantity'] += 3500
    elif 0 < WH_1.loc[i, 'stock_quantity'] <= 100:
        WH_1.loc[i, 'stock_quantity'] += 3200
    elif 100 < WH_1.loc[i, 'stock_quantity'] <= 500:
        WH_1.loc[i, 'stock_quantity'] += 2750
    elif 500 < WH_1.loc[i, 'stock_quantity'] <= 1500:
        WH_1.loc[i, 'stock_quantity'] += 2000
    elif 1500 < WH_1.loc[i, 'stock_quantity'] <= 3000:
        WH_1.loc[i, 'stock_quantity'] += 1500
    elif 3000 < WH_1.loc[i, 'stock_quantity'] <= 4000:
        WH_1.loc[i, 'stock_quantity'] += 1000
    elif 4000 < WH_1.loc[i, 'stock_quantity'] <= 6000:
        WH_1.loc[i, 'stock_quantity'] += 500

In [11]:
WH_1.head(10)

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-1FPK,Coffee Maker Automatic,Home,Kitchen,Nike,3.2,3112,3299,120.51,Economy,1.97,5,Netherlands,UK,3
1,PRD-C6UZ,Yoga Mat Non-Slip,Health,Supplements,Asus,3.8,3758,2896,60.33,Next Day,5.48,3,United States,UK,1
2,PRD-T2TA,Blender 1000W,Home,Furniture,Asus,3.0,2973,2899,295.89,Economy,20.40,13,France,UK,2
3,PRD-IROD,Badminton Racket,Sports,Accessories,Adidas,3.8,3825,2884,186.33,Express,4.76,8,Italy,USA-West,3
4,PRD-LBR7,Screen Protector Tempered Glass,Electronics,Cameras,Anker,3.1,4160,3282,427.16,Standard,15.48,7,Germany,UK,3
5,PRD-60FK,Coffee Maker Automatic,Home,Kitchen,Nike,3.4,2162,2517,156.79,Express,15.93,5,France,USA-West,5
6,PRD-253J,Air Fryer 5L,Home,Appliances,Logitech,4.7,3855,2977,75.88,Express,9.96,5,Canada,USA-East,3
7,PRD-LOOK,Electric Toothbrush,Home,Bedding,Baseus,3.8,3105,2693,229.48,Next Day,5.25,13,Australia,UK,3
8,PRD-2H2Z,Phone Case Shockproof,Electronics,Smartphones,Samsung,4.1,994,3217,75.34,Economy,22.43,12,Italy,Asia-Pacific,2
9,PRD-48P0,Storage Box Set,Home,Appliances,Nikon,4.8,3999,2974,96.42,Economy,22.99,10,Belgium,UK,4

In [12]:
WH_2 = pd.read_csv('warehouse_2.csv')

In [13]:
WH_2 = WH_2[['product_id', 'product_name', 'category','sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
'stock_quantity', 'unit_price_usd','shipping_method', 'shipping_cost_usd', 'delivery_days', 'shipping_country', 'warehouse_location','rating']]

In [14]:
df_cleaned2 = WH_2.drop_duplicates(subset='product_id', keep='first')

In [15]:
WH_2 = df_cleaned2.copy()

In [16]:
len(WH_2)

97029

In [17]:
WH_2 = WH_2.copy()
for i in WH_2.index:
    if WH_2.loc[i, 'stock_quantity'] <= 0:
        WH_2.loc[i, 'stock_quantity'] += 8500
    elif 0 < WH_2.loc[i, 'stock_quantity'] <= 100:
        WH_2.loc[i, 'stock_quantity'] += 7200
    elif 100 < WH_2.loc[i, 'stock_quantity'] <= 500:
        WH_2.loc[i, 'stock_quantity'] += 10750
    elif 500 < WH_2.loc[i, 'stock_quantity'] <= 1500:
        WH_2.loc[i, 'stock_quantity'] += 6000
    elif 1500 < WH_2.loc[i, 'stock_quantity'] <= 3000:
        WH_2.loc[i, 'stock_quantity'] += 4500
    elif 3000 < WH_2.loc[i, 'stock_quantity'] <= 4000:
        WH_2.loc[i, 'stock_quantity'] += 9000
    elif 4000 < WH_2.loc[i, 'stock_quantity'] <= 6000:
        WH_2.loc[i, 'stock_quantity'] += 3500

In [18]:
WH_2.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-19SN,Massage Gun Deep Tissue,Health,Personal Care,Sony,4.2,4390,6920,31.36,Standard,0.44,11,Germany,USA-West,3
1,PRD-LF1R,Digital Thermometer,Health,Fitness,Sony,4.9,4297,10922,12.01,Standard,8.58,2,Belgium,USA-West,4
2,PRD-KYR8,Badminton Racket,Sports,Gym Equipment,Baseus,4.2,2630,6955,163.96,Economy,14.49,11,Belgium,Asia-Pacific,5
3,PRD-V4Y8,Casual Sneakers,Clothing,Shoes,Samsung,4.6,2986,11238,20.80,Standard,22.99,13,United States,Asia-Pacific,3
4,PRD-RROG,Swimming Goggles,Sports,Accessories,Xiaomi,4.3,1392,6753,112.86,Next Day,23.13,2,Netherlands,USA-East,4

In [19]:
WH_3 = pd.read_csv('warehouse_3.csv')

In [20]:
WH_3 = WH_3[['product_id', 'product_name', 'category','sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
'stock_quantity', 'unit_price_usd','shipping_method', 'shipping_cost_usd', 'delivery_days', 'shipping_country', 'warehouse_location','rating']]

In [21]:
df_cleaned3 = WH_3.drop_duplicates(subset='product_id', keep='first')

In [22]:
WH_3 = df_cleaned3.copy()

In [23]:
WH_3 = WH_3.copy()
for i in WH_3.index:
    if WH_3.loc[i, 'stock_quantity'] <= 0:
        WH_3.loc[i, 'stock_quantity'] += 2500
    elif 0 < WH_3.loc[i, 'stock_quantity'] <= 100:
        WH_3.loc[i, 'stock_quantity'] += 3200
    elif 100 < WH_3.loc[i, 'stock_quantity'] <= 500:
        WH_3.loc[i, 'stock_quantity'] += 1750
    elif 500 < WH_3.loc[i, 'stock_quantity'] <= 1500:
        WH_3.loc[i, 'stock_quantity'] += 7000
    elif 1500 < WH_3.loc[i, 'stock_quantity'] <= 3000:
        WH_3.loc[i, 'stock_quantity'] += 9500
    elif 3000 < WH_3.loc[i, 'stock_quantity'] <= 4000:
        WH_3.loc[i, 'stock_quantity'] += 4000
    elif 4000 < WH_3.loc[i, 'stock_quantity'] <= 6000:
        WH_3.loc[i, 'stock_quantity'] += 2500

In [24]:
WH_3.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-GW74,Fitness Smart Band,Health,Supplements,Philips,3.3,991,2085,88.65,Economy,24.74,11,United Kingdom,UK,1
1,PRD-L466,Vitamin C Tablets,Health,Fitness,Dell,4.2,3924,7701,46.25,Economy,14.06,2,United States,EU-Central,1
2,PRD-447S,Hooded Sweatshirt,Clothing,Accessories,Lenovo,4.1,767,7725,39.41,Economy,6.36,2,Australia,USA-East,5
3,PRD-FNDR,Exercise Ball,Sports,Outdoor,Asus,3.5,2760,7954,225.05,Express,10.16,12,Italy,UK,5
4,PRD-LTA4,Vacuum Robot Cleaner,Home,Appliances,Philips,3.4,203,2134,158.21,Next Day,1.36,9,Australia,Asia-Pacific,1

In [25]:
WH_4 = pd.read_csv('warehouse_4.csv')

In [26]:
WH_4 = WH_4[['product_id', 'product_name', 'category','sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
'stock_quantity', 'unit_price_usd','shipping_method', 'shipping_cost_usd', 'delivery_days', 'shipping_country', 'warehouse_location','rating']]

In [27]:
df_cleaned4 = WH_4.drop_duplicates(subset='product_id', keep='first')

In [28]:
WH_4 = df_cleaned4.copy()

In [29]:
WH_4 = WH_4.copy()
for i in WH_4.index:
    if WH_4.loc[i, 'stock_quantity'] <= 0:
        WH_4.loc[i, 'stock_quantity'] += 2500
    elif 0 < WH_4.loc[i, 'stock_quantity'] <= 100:
        WH_4.loc[i, 'stock_quantity'] += 3200
    elif 100 < WH_4.loc[i, 'stock_quantity'] <= 500:
        WH_4.loc[i, 'stock_quantity'] += 1750
    elif 500 < WH_4.loc[i, 'stock_quantity'] <= 1500:
        WH_4.loc[i, 'stock_quantity'] += 7000
    elif 1500 < WH_4.loc[i, 'stock_quantity'] <= 3000:
        WH_4.loc[i, 'stock_quantity'] += 9500
    elif 3000 < WH_4.loc[i, 'stock_quantity'] <= 4000:
        WH_4.loc[i, 'stock_quantity'] += 4000
    elif 4000 < WH_4.loc[i, 'stock_quantity'] <= 6000:
        WH_4.loc[i, 'stock_quantity'] += 2500

In [30]:
WH_4.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-RF99,Fitness Smart Band,Health,Medical Devices,Philips,4.8,3108,2248,33.40,Economy,7.12,11,Canada,EU-Central,2
1,PRD-ZUU5,Massage Gun Deep Tissue,Health,Personal Care,Lenovo,3.1,421,7839,43.13,Express,12.11,8,Belgium,EU-Central,3
2,PRD-XVL0,Coffee Maker Automatic,Home,Bedding,Nike,3.8,3508,1873,121.90,Standard,16.99,11,Canada,USA-West,1
3,PRD-FET8,Desk Lamp LED,Home,Decor,Philips,3.4,4913,7893,274.97,Economy,23.71,1,Australia,USA-West,1
4,PRD-6CAB,Sports Bra High Impact,Clothing,Accessories,Dell,3.9,458,2205,55.09,Next Day,7.82,10,Australia,Asia-Pacific,4

In [31]:
WH_5 = pd.read_csv('warehouse_5.csv')

In [32]:
WH_5 = WH_5[['product_id', 'product_name', 'category','sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
'stock_quantity', 'unit_price_usd','shipping_method', 'shipping_cost_usd', 'delivery_days', 'shipping_country', 'warehouse_location','rating']]

In [33]:
df_cleaned5 = WH_5.drop_duplicates(subset='product_id', keep='first')

In [34]:
WH_5 = df_cleaned5.copy()

In [35]:
WH_5 = WH_5.copy()
for i in WH_5.index:
    if WH_5.loc[i, 'stock_quantity'] <= 0:
        WH_5.loc[i, 'stock_quantity'] += 2500
    elif 0 < WH_5.loc[i, 'stock_quantity'] <= 100:
        WH_5.loc[i, 'stock_quantity'] += 3200
    elif 100 < WH_5.loc[i, 'stock_quantity'] <= 500:
        WH_5.loc[i, 'stock_quantity'] += 1750
    elif 500 < WH_5.loc[i, 'stock_quantity'] <= 1500:
        WH_5.loc[i, 'stock_quantity'] += 7000
    elif 1500 < WH_5.loc[i, 'stock_quantity'] <= 3000:
        WH_5.loc[i, 'stock_quantity'] += 9500
    elif 3000 < WH_5.loc[i, 'stock_quantity'] <= 4000:
        WH_5.loc[i, 'stock_quantity'] += 4000
    elif 4000 < WH_5.loc[i, 'stock_quantity'] <= 6000:
        WH_5.loc[i, 'stock_quantity'] += 2500

In [36]:
WH_5.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-RFT3,Power Bank 20000mAh,Electronics,Cameras,Nike,3.3,838,7880,234.75,Economy,6.79,7,Canada,USA-West,3
1,PRD-ZAV4,Casual Sneakers,Clothing,Kids Wear,Dell,3.1,4613,7839,69.80,Economy,4.35,2,Australia,Asia-Pacific,1
2,PRD-9TVA,Denim Jeans Slim Fit,Clothing,Kids Wear,Baseus,3.1,1683,1925,130.34,Standard,4.19,1,France,EU-Central,3
3,PRD-8G5U,Vitamin C Tablets,Health,Fitness,Adidas,4.1,3738,7634,186.11,Economy,24.03,6,United States,Asia-Pacific,3
4,PRD-A2L4,Blender 1000W,Home,Kitchen,Baseus,4.0,2470,1926,85.77,Express,2.40,8,Canada,USA-West,2

In [37]:
WH_6 = pd.read_csv('warehouse_6.csv')

In [38]:
WH_6 = WH_6[['product_id', 'product_name', 'category','sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
'stock_quantity', 'unit_price_usd','shipping_method', 'shipping_cost_usd', 'delivery_days', 'shipping_country', 'warehouse_location','rating']]

In [39]:
df_cleaned6 = WH_6.drop_duplicates(subset='product_id', keep='first')

In [40]:
WH_6 = df_cleaned6.copy()

In [41]:
WH_6 = WH_6.copy()
for i in WH_6.index:
    if WH_6.loc[i, 'stock_quantity'] <= 0:
        WH_6.loc[i, 'stock_quantity'] += 11500
    elif 0 < WH_6.loc[i, 'stock_quantity'] <= 100:
        WH_6.loc[i, 'stock_quantity'] += 200
    elif 100 < WH_6.loc[i, 'stock_quantity'] <= 500:
        WH_6.loc[i, 'stock_quantity'] += 750
    elif 500 < WH_6.loc[i, 'stock_quantity'] <= 1500:
        WH_6.loc[i, 'stock_quantity'] += 10000
    elif 1500 < WH_6.loc[i, 'stock_quantity'] <= 3000:
        WH_6.loc[i, 'stock_quantity'] += 2500
    elif 3000 < WH_6.loc[i, 'stock_quantity'] <= 4000:
        WH_6.loc[i, 'stock_quantity'] += 1000
    elif 4000 < WH_6.loc[i, 'stock_quantity'] <= 6000:
        WH_6.loc[i, 'stock_quantity'] += 4500

In [42]:
WH_6.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-DJ3N,Fitness Smart Band,Health,Fitness,Canon,4.2,467,10899,188.17,Standard,10.50,13,Germany,USA-West,2
1,PRD-4NVJ,Portable SSD 1TB,Electronics,Laptops,JBL,4.7,3327,10992,369.32,Standard,18.13,13,Belgium,USA-East,3
2,PRD-HYLX,Casual Sneakers,Clothing,Accessories,HP,3.1,2645,10984,101.11,Economy,6.10,2,Netherlands,Asia-Pacific,3
3,PRD-3Y3J,Casual Sneakers,Clothing,Womens Wear,Sony,4.0,727,954,48.75,Next Day,18.27,1,Canada,UK,3
4,PRD-FGFR,Gym Gloves,Sports,Sports Wear,GoPro,3.7,1219,953,247.38,Next Day,12.40,4,United Kingdom,USA-East,2

In [43]:
WH_7 = pd.read_csv('warehouse_7.csv')

In [44]:
WH_7 = WH_7[['product_id', 'product_name', 'category','sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
'stock_quantity', 'unit_price_usd','shipping_method', 'shipping_cost_usd', 'delivery_days', 'shipping_country', 'warehouse_location','rating']]

In [45]:
df_cleaned7 = WH_7.drop_duplicates(subset='product_id', keep='first')

In [46]:
WH_7 = df_cleaned7.copy()

In [47]:
WH_7 = WH_7.copy()
for i in WH_7.index:
    if WH_7.loc[i, 'stock_quantity'] <= 0:
        WH_7.loc[i, 'stock_quantity'] += 1500
    elif 0 < WH_7.loc[i, 'stock_quantity'] <= 100:
        WH_7.loc[i, 'stock_quantity'] += 6200
    elif 100 < WH_7.loc[i, 'stock_quantity'] <= 500:
        WH_7.loc[i, 'stock_quantity'] += 7050
    elif 500 < WH_7.loc[i, 'stock_quantity'] <= 1500:
        WH_7.loc[i, 'stock_quantity'] += 1000
    elif 1500 < WH_7.loc[i, 'stock_quantity'] <= 3000:
        WH_7.loc[i, 'stock_quantity'] += 8500
    elif 3000 < WH_7.loc[i, 'stock_quantity'] <= 4000:
        WH_7.loc[i, 'stock_quantity'] += 100
    elif 4000 < WH_7.loc[i, 'stock_quantity'] <= 6000:
        WH_7.loc[i, 'stock_quantity'] += 450

In [48]:
WH_7.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-7DGH,Badminton Racket,Sports,Outdoor,Logitech,4.0,3269,1529,245.23,Economy,4.97,7,United States,UK,2
1,PRD-FG4P,Desk Lamp LED,Home,Bedding,Asus,3.3,105,1893,175.16,Economy,5.55,8,United Kingdom,USA-East,3
2,PRD-ZU1E,Vacuum Robot Cleaner,Home,Bedding,Lenovo,4.0,1687,7402,137.19,Standard,15.01,12,Spain,UK,4
3,PRD-ELVG,USB-C Fast Charger 65W,Electronics,Laptops,Adidas,4.2,3084,1620,389.75,Economy,0.30,2,Spain,Asia-Pacific,2
4,PRD-NUSS,Smart Watch Series 8,Electronics,Smartphones,Nikon,3.8,3749,7187,115.53,Express,5.42,14,Italy,USA-East,2

In [49]:
WH_8 = pd.read_csv('warehouse_8.csv')

In [50]:
WH_8 = WH_8[['product_id', 'product_name', 'category','sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
'stock_quantity', 'unit_price_usd','shipping_method', 'shipping_cost_usd', 'delivery_days', 'shipping_country', 'warehouse_location','rating']]

In [51]:
df_cleaned8 = WH_8.drop_duplicates(subset='product_id', keep='first')

In [52]:
WH_8 = df_cleaned8.copy()

In [53]:
WH_8 = WH_8.copy()
for i in WH_8.index:
    if WH_8.loc[i, 'stock_quantity'] <= 0:
        WH_8.loc[i, 'stock_quantity'] += 900
    elif 0 < WH_8.loc[i, 'stock_quantity'] <= 100:
        WH_8.loc[i, 'stock_quantity'] += 2800
    elif 100 < WH_8.loc[i, 'stock_quantity'] <= 500:
        WH_8.loc[i, 'stock_quantity'] += 5750
    elif 500 < WH_8.loc[i, 'stock_quantity'] <= 1500:
        WH_8.loc[i, 'stock_quantity'] += 4000
    elif 1500 < WH_8.loc[i, 'stock_quantity'] <= 3000:
        WH_8.loc[i, 'stock_quantity'] += 7500
    elif 3000 < WH_8.loc[i, 'stock_quantity'] <= 4000:
        WH_8.loc[i, 'stock_quantity'] += 8000
    elif 4000 < WH_8.loc[i, 'stock_quantity'] <= 6000:
        WH_8.loc[i, 'stock_quantity'] += 4500

In [54]:
WH_8.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-XHZK,Gym Gloves,Sports,Gym Equipment,Logitech,3.5,4734,6226,143.11,Standard,7.36,10,Italy,EU-Central,4
1,PRD-X3AX,Electric Toothbrush,Home,Decor,HP,4.3,2075,6094,287.96,Next Day,17.05,7,Italy,USA-East,1
2,PRD-ANIR,4K Webcam Pro,Electronics,Cameras,Huawei,3.6,583,5990,72.42,Next Day,18.55,11,Spain,UK,5
3,PRD-33J1,Electric Toothbrush,Home,Decor,GoPro,3.3,4018,6174,268.53,Economy,19.07,11,Spain,Asia-Pacific,2
4,PRD-ISU3,Gym Gloves,Sports,Accessories,JBL,4.3,1604,4793,208.95,Standard,12.87,1,Italy,Asia-Pacific,3

In [55]:
WH_9 = pd.read_csv('warehouse_9.csv')

In [56]:
WH_9 = WH_9[['product_id', 'product_name', 'category','sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
'stock_quantity', 'unit_price_usd','shipping_method', 'shipping_cost_usd', 'delivery_days', 'shipping_country', 'warehouse_location','rating']]

In [57]:
df_cleaned9 = WH_9.drop_duplicates(subset='product_id', keep='first')

In [58]:
WH_9 = df_cleaned9.copy()

In [59]:
WH_9 = WH_9.copy()
for i in WH_9.index:
    if WH_9.loc[i, 'stock_quantity'] <= 0:
        WH_9.loc[i, 'stock_quantity'] += 9800
    elif 0 < WH_9.loc[i, 'stock_quantity'] <= 100:
        WH_9.loc[i, 'stock_quantity'] += 4200
    elif 100 < WH_9.loc[i, 'stock_quantity'] <= 500:
        WH_9.loc[i, 'stock_quantity'] += 1750
    elif 500 < WH_9.loc[i, 'stock_quantity'] <= 1500:
        WH_9.loc[i, 'stock_quantity'] += 10200
    elif 1500 < WH_9.loc[i, 'stock_quantity'] <= 3000:
        WH_9.loc[i, 'stock_quantity'] += 4500
    elif 3000 < WH_9.loc[i, 'stock_quantity'] <= 4000:
        WH_9.loc[i, 'stock_quantity'] += 2000
    elif 4000 < WH_9.loc[i, 'stock_quantity'] <= 6000:
        WH_9.loc[i, 'stock_quantity'] += 500

In [60]:
WH_9.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-4Q9H,Coffee Maker Automatic,Home,Furniture,GoPro,4.2,278,10750,297.07,Economy,2.13,9,Belgium,Asia-Pacific,5
1,PRD-G0CC,Yoga Pants Leggings,Clothing,Kids Wear,Nike,4.8,1228,4267,64.96,Economy,10.21,13,United States,UK,3
2,PRD-PTJZ,4K Webcam Pro,Electronics,Cameras,Fitbit,4.4,4761,11025,422.81,Next Day,20.55,10,Italy,USA-West,5
3,PRD-QSL0,Gaming Mechanical Keyboard RGB,Electronics,Tablets,Sony,3.4,3387,10961,329.26,Next Day,1.66,11,Belgium,USA-East,5
4,PRD-BTM0,Treadmill Folding,Sports,Outdoor,Asus,4.6,4580,4293,219.70,Next Day,20.13,1,Germany,EU-Central,4

In [61]:
WH_10 = pd.read_csv('warehouse_10.csv')

In [62]:
WH_10 = WH_10[['product_id', 'product_name', 'category','sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
'stock_quantity', 'unit_price_usd','shipping_method', 'shipping_cost_usd', 'delivery_days', 'shipping_country', 'warehouse_location','rating']]

In [63]:
df_cleaned10 = WH_10.drop_duplicates(subset='product_id', keep='first')

In [64]:
WH_10 = df_cleaned10.copy()

In [65]:
WH_10 = WH_10.copy()
for i in WH_10.index:
    if WH_10.loc[i, 'stock_quantity'] <= 0:
        WH_10.loc[i, 'stock_quantity'] += 800
    elif 0 < WH_10.loc[i, 'stock_quantity'] <= 100:
        WH_10.loc[i, 'stock_quantity'] += 6700
    elif 100 < WH_10.loc[i, 'stock_quantity'] <= 500:
        WH_10.loc[i, 'stock_quantity'] += 1650
    elif 500 < WH_10.loc[i, 'stock_quantity'] <= 1500:
        WH_10.loc[i, 'stock_quantity'] += 1200
    elif 1500 < WH_10.loc[i, 'stock_quantity'] <= 3000:
        WH_10.loc[i, 'stock_quantity'] += 9500
    elif 3000 < WH_10.loc[i, 'stock_quantity'] <= 4000:
        WH_10.loc[i, 'stock_quantity'] += 2800
    elif 4000 < WH_10.loc[i, 'stock_quantity'] <= 6000:
        WH_10.loc[i, 'stock_quantity'] += 3500

In [66]:
WH_10.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-FK21,Casual Sneakers,Clothing,Womens Wear,Sony,4.1,782,1954,45.11,Economy,9.56,5,Canada,UK,1
1,PRD-DAO5,Coffee Maker Automatic,Home,Kitchen,Logitech,5.0,3251,2044,139.85,Express,16.23,9,Netherlands,UK,2
2,PRD-2CZI,Exercise Ball,Sports,Gym Equipment,Apple,4.7,4518,1834,41.35,Standard,16.87,9,United Kingdom,Asia-Pacific,5
3,PRD-DKZH,Swimming Goggles,Sports,Outdoor,Adidas,3.2,2499,1921,24.02,Express,8.56,9,Spain,USA-West,1
4,PRD-361U,Blender 1000W,Home,Kitchen,Baseus,4.6,4742,2008,261.84,Economy,14.84,10,Spain,Asia-Pacific,5

In [67]:
WH_11 = pd.read_csv('warehouse_11.csv')

In [68]:
WH_11 = WH_11[['product_id', 'product_name', 'category','sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
'stock_quantity', 'unit_price_usd','shipping_method', 'shipping_cost_usd', 'delivery_days', 'shipping_country', 'warehouse_location','rating']]

In [69]:
df_cleaned11 = WH_11.drop_duplicates(subset='product_id', keep='first')

In [70]:
WH_11 = df_cleaned11.copy()

In [71]:
WH_11 = WH_11.copy()
for i in WH_11.index:
    if WH_11.loc[i, 'stock_quantity'] <= 0:
        WH_11.loc[i, 'stock_quantity'] += 700
    elif 0 < WH_11.loc[i, 'stock_quantity'] <= 100:
        WH_11.loc[i, 'stock_quantity'] += 600
    elif 100 < WH_11.loc[i, 'stock_quantity'] <= 500:
        WH_11.loc[i, 'stock_quantity'] += 650
    elif 500 < WH_11.loc[i, 'stock_quantity'] <= 1500:
        WH_11.loc[i, 'stock_quantity'] += 1200
    elif 1500 < WH_11.loc[i, 'stock_quantity'] <= 3000:
        WH_11.loc[i, 'stock_quantity'] += 550
    elif 3000 < WH_11.loc[i, 'stock_quantity'] <= 4000:
        WH_11.loc[i, 'stock_quantity'] += 450
    elif 4000 < WH_11.loc[i, 'stock_quantity'] <= 6000:
        WH_11.loc[i, 'stock_quantity'] += 8700

In [72]:
WH_11.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,unit_price_usd,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,rating
0,PRD-N1J8,Jump Rope Speed,Sports,Accessories,Baseus,4.4,3686,1782,180.82,Standard,22.63,5,Belgium,Asia-Pacific,3
1,PRD-KKSN,Bedsheet Set Cotton,Home,Bedding,Xiaomi,4.7,712,1011,299.36,Express,7.01,12,Canada,Asia-Pacific,4
2,PRD-FTQY,USB-C Fast Charger 65W,Electronics,Smartphones,Xiaomi,4.8,3813,2143,260.41,Next Day,4.92,6,Belgium,UK,3
3,PRD-HBBP,Blender 1000W,Home,Decor,Apple,4.7,1064,988,231.37,Next Day,0.99,13,Netherlands,USA-East,2
4,PRD-QBSN,Fitness Smart Band,Health,Supplements,Nike,4.2,3316,1128,55.87,Next Day,0.56,1,Belgium,USA-West,3

In [73]:
WH_1['warehouse_id'] = 'W1'
WH_1['warehouse_location'] = 'Rochester'

WH_2['warehouse_id'] = 'W2'
WH_2['warehouse_location'] = 'Buffalo'

WH_3['warehouse_id'] = 'W3'
WH_3['warehouse_location'] = 'Syracruse'

WH_4['warehouse_id'] = 'W4'
WH_4['warehouse_location'] = 'Albany'

WH_5['warehouse_id'] = 'W5'
WH_5['warehouse_location'] = 'Utica'

WH_6['warehouse_id'] = 'W6'
WH_6['warehouse_location'] = 'New Rochelle'

WH_7['warehouse_id'] = 'W7'
WH_7['warehouse_location'] = 'Schenectady'

WH_8['warehouse_id'] = 'W8'
WH_8['warehouse_location'] = 'Yonkers'

WH_9['warehouse_id'] = 'W9'
WH_9['warehouse_location'] = 'Mount Vernon'

WH_10['warehouse_id'] = 'W10'
WH_10['warehouse_location'] = 'Hempstead'

WH_11['warehouse_id'] = 'W11'
WH_11['warehouse_location'] = 'Webster'

In [74]:
warehouse_df = pd.concat([WH_1, WH_2, WH_3, WH_4, WH_5, WH_6, WH_7, WH_8, WH_9, WH_10, WH_11], ignore_index=True)

In [75]:
len(warehouse_df)

970795

## Warehouse optimization

In [76]:
import numpy as np
from docplex.mp.model import Model

In [77]:
distance_map = {
    'Rochester': 150,
    'Buffalo': 280,
    'Syracruse': 155,
    'Albany': 200,
    'Utica': 180,
    'New Rochelle': 50,
    'Schenectady': 300,
    'Yonkers': 80,
    'Mount Vernon': 240,
    'Hempstead': 25,
    'Webster': 110
}

In [78]:
warehouse_df['distance_to_store'] = (
    warehouse_df['warehouse_location']
    .map(distance_map)
    .fillna(1500)
)

In [79]:
warehouse_df['transport_cost_per_unit'] = (
    warehouse_df['shipping_cost_usd']/warehouse_df['stock_quantity']
        .replace(0, 1)
)

In [80]:
warehouse_df['lead_time_days'] = (warehouse_df['delivery_days'])

In [81]:
warehouse_opt_df = warehouse_df[['warehouse_id','warehouse_location','product_id','product_name', 'category',
       'sub_category', 'brand','stock_quantity','distance_to_store','transport_cost_per_unit','lead_time_days'
]].rename(columns={
    'stock_quantity': 'available_stock'
})

In [82]:
forecast_df = pd.read_csv('inventory_forecast_output.csv', on_bad_lines='skip')

In [83]:
reorder_df = forecast_df[forecast_df['reorder_quantity'] > 0].copy()

In [84]:
mdl = Model(name='inventory_optimization')

In [85]:
x = {}

for _, r in reorder_df.iterrows():

    p = r['product_id']

    candidate_wh = warehouse_opt_df[
        warehouse_opt_df['product_id'] == p
    ]

    for _, w in candidate_wh.iterrows():

        key = (w['warehouse_id'], p)

        x[key] = mdl.continuous_var(
            lb=0,
            name=f"x_{w['warehouse_id']}_{p}"
        )

Warning: Duplicate variable name: x_W1_PRD-H8LS already used for docplex.mp.Var(type=C,name='x_W1_PRD-H8LS')
Warning: Duplicate variable name: x_W2_PRD-H8LS already used for docplex.mp.Var(type=C,name='x_W2_PRD-H8LS')
Warning: Duplicate variable name: x_W3_PRD-H8LS already used for docplex.mp.Var(type=C,name='x_W3_PRD-H8LS')
Warning: Duplicate variable name: x_W7_PRD-H8LS already used for docplex.mp.Var(type=C,name='x_W7_PRD-H8LS')
Warning: Duplicate variable name: x_W4_PRD-8F6N already used for docplex.mp.Var(type=C,name='x_W4_PRD-8F6N')
Warning: Duplicate variable name: x_W3_PRD-XU6A already used for docplex.mp.Var(type=C,name='x_W3_PRD-XU6A')
Warning: Duplicate variable name: x_W5_PRD-XU6A already used for docplex.mp.Var(type=C,name='x_W5_PRD-XU6A')
Warning: Duplicate variable name: x_W7_PRD-XU6A already used for docplex.mp.Var(type=C,name='x_W7_PRD-XU6A')
Warning: Duplicate variable name: x_W10_PRD-XU6A already used for docplex.mp.Var(type=C,name='x_W10_PRD-XU6A')
Warning: Duplicate variable name: x_W6_PRD-0C3W already used for docplex.mp.Var(type=C,name='x_W6_PRD-0C3W')
Warning: Duplicate variable name: x_W8_PRD-0C3W already used for docplex.mp.Var(type=C,name='x_W8_PRD-0C3W')
Warning: Duplicate variable name: x_W1_PRD-9Y2R already used for docplex.mp.Var(type=C,name='x_W1_PRD-9Y2R')
Warning: Duplicate variable name: x_W4_PRD-9Y2R already used for docplex.mp.Var(type=C,name='x_W4_PRD-9Y2R')
Warning: Duplicate variable name: x_W2_PRD-PX3Q already used for docplex.mp.Var(type=C,name='x_W2_PRD-PX3Q')
Warning: Duplicate variable name: x_W4_PRD-PX3Q already used for docplex.mp.Var(type=C,name='x_W4_PRD-PX3Q')
Warning: Duplicate variable name: x_W8_PRD-PX3Q already used for docplex.mp.Var(type=C,name='x_W8_PRD-PX3Q')
Warning: Duplicate variable name: x_W9_PRD-PX3Q already used for docplex.mp.Var(type=C,name='x_W9_PRD-PX3Q')
Warning: Duplicate variable name: x_W3_PRD-OHAH already used for docplex.mp.Var(type=C,name='x_W3_PRD-OHAH')
Warning: Duplicate variable name: x_W10_PRD-OHAH already used for docplex.mp.Var(type=C,name='x_W10_PRD-OHAH')
Warning: Duplicate variable name: x_W2_PRD-P8AT already used for docplex.mp.Var(type=C,name='x_W2_PRD-P8AT')
Warning: Duplicate variable name: x_W6_PRD-P8AT already used for docplex.mp.Var(type=C,name='x_W6_PRD-P8AT')
Warning: Duplicate variable name: x_W1_PRD-KCMK already used for docplex.mp.Var(type=C,name='x_W1_PRD-KCMK')
Warning: Duplicate variable name: x_W2_PRD-KCMK already used for docplex.mp.Var(type=C,name='x_W2_PRD-KCMK')
Warning: Duplicate variable name: x_W3_PRD-KCMK already used for docplex.mp.Var(type=C,name='x_W3_PRD-KCMK')
Warning: Duplicate variable name: x_W8_PRD-J64Z already used for docplex.mp.Var(type=C,name='x_W8_PRD-J64Z')
Warning: Duplicate variable name: x_W9_PRD-J64Z already used for docplex.mp.Var(type=C,name='x_W9_PRD-J64Z')
Warning: Duplicate variable name: x_W2_PRD-JPT0 already used for docplex.mp.Var(type=C,name='x_W2_PRD-JPT0')
Warning: Duplicate variable name: x_W5_PRD-JPT0 already used for docplex.mp.Var(type=C,name='x_W5_PRD-JPT0')
Warning: Duplicate variable name: x_W6_PRD-JPT0 already used for docplex.mp.Var(type=C,name='x_W6_PRD-JPT0')
Warning: Duplicate variable name: x_W1_PRD-JOIR already used for docplex.mp.Var(type=C,name='x_W1_PRD-JOIR')
Warning: Duplicate variable name: x_W2_PRD-JOIR already used for docplex.mp.Var(type=C,name='x_W2_PRD-JOIR')
Warning: Duplicate variable name: x_W7_PRD-JCAL already used for docplex.mp.Var(type=C,name='x_W7_PRD-JCAL')
Warning: Duplicate variable name: x_W10_PRD-JCAL already used for docplex.mp.Var(type=C,name='x_W10_PRD-JCAL')
Warning: Duplicate variable name: x_W6_PRD-MGAL already used for docplex.mp.Var(type=C,name='x_W6_PRD-MGAL')
Warning: Duplicate variable name: x_W9_PRD-MGAL already used for docplex.mp.Var(type=C,name='x_W9_PRD-MGAL')
Warning: Duplicate variable name: x_W7_PRD-MLKP already used for docplex.mp.Var(type=C,name='x_W7_PRD-MLKP')
Warning: Duplicate variable name: x_W10_PRD-MLKP already used for docplex.mp.Var(type=C,name='x_W10_PRD-MLKP')
Warning: Duplicate variable name: x_W2_PRD-LMX7 already used for docplex.mp.Var(type=C,name='x_W2_PRD-LMX7')
Warning: Duplicate variable name: x_W8_PRD-LMX7 already used for docplex.mp.Var(type=C,name='x_W8_PRD-LMX7')
Warning: Duplicate variable name: x_W5_PRD-X898 already used for docplex.mp.Var(type=C,name='x_W5_PRD-X898')
Warning: Duplicate variable name: x_W7_PRD-X898 already used for docplex.mp.Var(type=C,name='x_W7_PRD-X898')
Warning: Duplicate variable name: x_W10_PRD-X898 already used for docplex.mp.Var(type=C,name='x_W10_PRD-X898')
Warning: Duplicate variable name: x_W2_PRD-X9PD already used for docplex.mp.Var(type=C,name='x_W2_PRD-X9PD')
Warning: Duplicate variable name: x_W6_PRD-X9PD already used for docplex.mp.Var(type=C,name='x_W6_PRD-X9PD')
Warning: Duplicate variable name: x_W1_PRD-VG7Y already used for docplex.mp.Var(type=C,name='x_W1_PRD-VG7Y')
Warning: Duplicate variable name: x_W10_PRD-VG7Y already used for docplex.mp.Var(type=C,name='x_W10_PRD-VG7Y')
Warning: Duplicate variable name: x_W7_PRD-W0EU already used for docplex.mp.Var(type=C,name='x_W7_PRD-W0EU')
Warning: Duplicate variable name: x_W10_PRD-W0EU already used for docplex.mp.Var(type=C,name='x_W10_PRD-W0EU')
Warning: Duplicate variable name: x_W5_PRD-ZRTL already used for docplex.mp.Var(type=C,name='x_W5_PRD-ZRTL')
Warning: Duplicate variable name: x_W7_PRD-ZRTL already used for docplex.mp.Var(type=C,name='x_W7_PRD-ZRTL')
Warning: Duplicate variable name: x_W4_PRD-ZNYA already used for docplex.mp.Var(type=C,name='x_W4_PRD-ZNYA')
Warning: Duplicate variable name: x_W8_PRD-ZNYA already used for docplex.mp.Var(type=C,name='x_W8_PRD-ZNYA')
Warning: Duplicate variable name: x_W1_PRD-Y89E already used for docplex.mp.Var(type=C,name='x_W1_PRD-Y89E')
Warning: Duplicate variable name: x_W4_PRD-Y89E already used for docplex.mp.Var(type=C,name='x_W4_PRD-Y89E')
Warning: Duplicate variable name: x_W8_PRD-Y89E already used for docplex.mp.Var(type=C,name='x_W8_PRD-Y89E')
Warning: Duplicate variable name: x_W5_PRD-YM7S already used for docplex.mp.Var(type=C,name='x_W5_PRD-YM7S')
Warning: Duplicate variable name: x_W8_PRD-YM7S already used for docplex.mp.Var(type=C,name='x_W8_PRD-YM7S')
Warning: Duplicate variable name: x_W3_PRD-YGQC already used for docplex.mp.Var(type=C,name='x_W3_PRD-YGQC')
Warning: Duplicate variable name: x_W6_PRD-YGQC already used for docplex.mp.Var(type=C,name='x_W6_PRD-YGQC')
Warning: Duplicate variable name: x_W4_PRD-RE1W already used for docplex.mp.Var(type=C,name='x_W4_PRD-RE1W')
Warning: Duplicate variable name: x_W10_PRD-RE1W already used for docplex.mp.Var(type=C,name='x_W10_PRD-RE1W')
Warning: Duplicate variable name: x_W4_PRD-TDVQ already used for docplex.mp.Var(type=C,name='x_W4_PRD-TDVQ')
Warning: Duplicate variable name: x_W6_PRD-TDVQ already used for docplex.mp.Var(type=C,name='x_W6_PRD-TDVQ')
Warning: Duplicate variable name: x_W4_PRD-U6TB already used for docplex.mp.Var(type=C,name='x_W4_PRD-U6TB')
Warning: Duplicate variable name: x_W8_PRD-U6TB already used for docplex.mp.Var(type=C,name='x_W8_PRD-U6TB')
Warning: Duplicate variable name: x_W7_PRD-TMYO already used for docplex.mp.Var(type=C,name='x_W7_PRD-TMYO')
Warning: Duplicate variable name: x_W7_PRD-TRNV already used for docplex.mp.Var(type=C,name='x_W7_PRD-TRNV')
Warning: Duplicate variable name: x_W8_PRD-TRNV already used for docplex.mp.Var(type=C,name='x_W8_PRD-TRNV')
Warning: Duplicate variable name: x_W10_PRD-TRNV already used for docplex.mp.Var(type=C,name='x_W10_PRD-TRNV')
Warning: Duplicate variable name: x_W1_PRD-5XKA already used for docplex.mp.Var(type=C,name='x_W1_PRD-5XKA')
Warning: Duplicate variable name: x_W2_PRD-5XKA already used for docplex.mp.Var(type=C,name='x_W2_PRD-5XKA')
Warning: Duplicate variable name: x_W5_PRD-5XKA already used for docplex.mp.Var(type=C,name='x_W5_PRD-5XKA')
Warning: Duplicate variable name: x_W6_PRD-5BCW already used for docplex.mp.Var(type=C,name='x_W6_PRD-5BCW')
Warning: Duplicate variable name: x_W9_PRD-5BCW already used for docplex.mp.Var(type=C,name='x_W9_PRD-5BCW')
Warning: Duplicate variable name: x_W1_PRD-5GE6 already used for docplex.mp.Var(type=C,name='x_W1_PRD-5GE6')
Warning: Duplicate variable name: x_W10_PRD-5GE6 already used for docplex.mp.Var(type=C,name='x_W10_PRD-5GE6')
Warning: Duplicate variable name: x_W4_PRD-1QFG already used for docplex.mp.Var(type=C,name='x_W4_PRD-1QFG')
Warning: Duplicate variable name: x_W8_PRD-1QFG already used for docplex.mp.Var(type=C,name='x_W8_PRD-1QFG')
Warning: Duplicate variable name: x_W1_PRD-270O already used for docplex.mp.Var(type=C,name='x_W1_PRD-270O')
Warning: Duplicate variable name: x_W2_PRD-270O already used for docplex.mp.Var(type=C,name='x_W2_PRD-270O')
Warning: Duplicate variable name: x_W6_PRD-270O already used for docplex.mp.Var(type=C,name='x_W6_PRD-270O')
Warning: Duplicate variable name: x_W4_PRD-1YGY already used for docplex.mp.Var(type=C,name='x_W4_PRD-1YGY')
Warning: Duplicate variable name: x_W6_PRD-1YGY already used for docplex.mp.Var(type=C,name='x_W6_PRD-1YGY')
Warning: Duplicate variable name: x_W7_PRD-1YGY already used for docplex.mp.Var(type=C,name='x_W7_PRD-1YGY')
Warning: Duplicate variable name: x_W2_PRD-0HKG already used for docplex.mp.Var(type=C,name='x_W2_PRD-0HKG')
Warning: Duplicate variable name: x_W10_PRD-0HKG already used for docplex.mp.Var(type=C,name='x_W10_PRD-0HKG')
Warning: Duplicate variable name: x_W10_PRD-2URD already used for docplex.mp.Var(type=C,name='x_W10_PRD-2URD')
Warning: Duplicate variable name: x_W6_PRD-2WGF already used for docplex.mp.Var(type=C,name='x_W6_PRD-2WGF')
Warning: Duplicate variable name: x_W8_PRD-2WGF already used for docplex.mp.Var(type=C,name='x_W8_PRD-2WGF')
Warning: Duplicate variable name: x_W5_PRD-30W9 already used for docplex.mp.Var(type=C,name='x_W5_PRD-30W9')
Warning: Duplicate variable name: x_W9_PRD-30W9 already used for docplex.mp.Var(type=C,name='x_W9_PRD-30W9')
Warning: Duplicate variable name: x_W6_PRD-FCO4 already used for docplex.mp.Var(type=C,name='x_W6_PRD-FCO4')
Warning: Duplicate variable name: x_W7_PRD-FCO4 already used for docplex.mp.Var(type=C,name='x_W7_PRD-FCO4')
Warning: Duplicate variable name: x_W3_PRD-FRGZ already used for docplex.mp.Var(type=C,name='x_W3_PRD-FRGZ')
Warning: Duplicate variable name: x_W9_PRD-FRGZ already used for docplex.mp.Var(type=C,name='x_W9_PRD-FRGZ')
Warning: Duplicate variable name: x_W1_PRD-EHBM already used for docplex.mp.Var(type=C,name='x_W1_PRD-EHBM')
Warning: Duplicate variable name: x_W2_PRD-EHBM already used for docplex.mp.Var(type=C,name='x_W2_PRD-EHBM')
Warning: Duplicate variable name: x_W4_PRD-EHBM already used for docplex.mp.Var(type=C,name='x_W4_PRD-EHBM')
Warning: Duplicate variable name: x_W1_PRD-EN83 already used for docplex.mp.Var(type=C,name='x_W1_PRD-EN83')
Warning: Duplicate variable name: x_W4_PRD-EN83 already used for docplex.mp.Var(type=C,name='x_W4_PRD-EN83')
Warning: Duplicate variable name: x_W10_PRD-EN83 already used for docplex.mp.Var(type=C,name='x_W10_PRD-EN83')
Warning: Duplicate variable name: x_W1_PRD-GTYZ already used for docplex.mp.Var(type=C,name='x_W1_PRD-GTYZ')
Warning: Duplicate variable name: x_W3_PRD-GTYZ already used for docplex.mp.Var(type=C,name='x_W3_PRD-GTYZ')
Warning: Duplicate variable name: x_W4_PRD-GCSJ already used for docplex.mp.Var(type=C,name='x_W4_PRD-GCSJ')
Warning: Duplicate variable name: x_W5_PRD-GCSJ already used for docplex.mp.Var(type=C,name='x_W5_PRD-GCSJ')
Warning: Duplicate variable name: x_W6_PRD-GCSJ already used for docplex.mp.Var(type=C,name='x_W6_PRD-GCSJ')
Warning: Duplicate variable name: x_W8_PRD-GCSJ already used for docplex.mp.Var(type=C,name='x_W8_PRD-GCSJ')
Warning: Duplicate variable name: x_W6_PRD-B39M already used for docplex.mp.Var(type=C,name='x_W6_PRD-B39M')
Warning: Duplicate variable name: x_W10_PRD-B39M already used for docplex.mp.Var(type=C,name='x_W10_PRD-B39M')
Warning: Duplicate variable name: x_W6_PRD-BNVE already used for docplex.mp.Var(type=C,name='x_W6_PRD-BNVE')
Warning: Duplicate variable name: x_W8_PRD-BNVE already used for docplex.mp.Var(type=C,name='x_W8_PRD-BNVE')
Warning: Duplicate variable name: x_W10_PRD-BNVE already used for docplex.mp.Var(type=C,name='x_W10_PRD-BNVE')
Warning: Duplicate variable name: x_W10_PRD-9U9I already used for docplex.mp.Var(type=C,name='x_W10_PRD-9U9I')
Warning: Duplicate variable name: x_W5_PRD-9TYC already used for docplex.mp.Var(type=C,name='x_W5_PRD-9TYC')
Warning: Duplicate variable name: x_W10_PRD-9TYC already used for docplex.mp.Var(type=C,name='x_W10_PRD-9TYC')
Warning: Duplicate variable name: x_W3_PRD-9HEK already used for docplex.mp.Var(type=C,name='x_W3_PRD-9HEK')
Warning: Duplicate variable name: x_W6_PRD-9HEK already used for docplex.mp.Var(type=C,name='x_W6_PRD-9HEK')
Warning: Duplicate variable name: x_W1_PRD-DOTV already used for docplex.mp.Var(type=C,name='x_W1_PRD-DOTV')
Warning: Duplicate variable name: x_W5_PRD-DOTV already used for docplex.mp.Var(type=C,name='x_W5_PRD-DOTV')
Warning: Duplicate variable name: x_W6_PRD-DOTV already used for docplex.mp.Var(type=C,name='x_W6_PRD-DOTV')
Warning: Duplicate variable name: x_W3_PRD-BUH3 already used for docplex.mp.Var(type=C,name='x_W3_PRD-BUH3')
Warning: Duplicate variable name: x_W5_PRD-BUH3 already used for docplex.mp.Var(type=C,name='x_W5_PRD-BUH3')

In [86]:
objective_terms = []

for _, w in warehouse_opt_df.iterrows():

    key = (w['warehouse_id'], w['product_id'])

    # Only use variables that exist
    if key in x:

        cost = (

            w['transport_cost_per_unit']

            + 0.01 * w['distance_to_store']

            + 2 * w['lead_time_days']

        )

        objective_terms.append(

            x[key] * cost

        )

objective = mdl.sum(objective_terms)

mdl.minimize(objective)

In [87]:
for _, r in reorder_df.iterrows():

    p = r['product_id']

    reorder_qty = r['reorder_quantity']

    candidate_wh = warehouse_opt_df[
        warehouse_opt_df['product_id'] == p
    ]

    mdl.add_constraint(

        mdl.sum(

            x[(w['warehouse_id'], p)]

            for _, w in candidate_wh.iterrows()

        )

        >=

        reorder_qty

    )

In [88]:
for _, w in warehouse_opt_df.iterrows():

    key = (w['warehouse_id'], w['product_id'])

    if key in x:

        mdl.add_constraint(

            x[key]

            <=

            w['available_stock']

        )

In [89]:
solution = mdl.solve(log_output=True)

print(solution)

Version identifier: 22.1.1.0 | 2022-11-28 | 9160aff4d
CPXPARAM_Read_DataCheck                          1
Parallel mode: deterministic, using up to 4 threads for concurrent optimization:
 * Starting dual Simplex on 1 thread...
 * Starting Barrier on 3 threads...
Tried aggregator 1 time.
LP Presolve eliminated 24335 rows and 6919 columns.
Reduced LP has 4738 rows, 10688 columns, and 10688 nonzeros.
Presolve time = 0.27 sec. (10.83 ticks)

Iteration log . . .
Iteration:     1   Dual objective     =       1564076.507140
Iteration:   441   Dual objective     =       1719116.057399
Iteration:   882   Dual objective     =       1831247.812408
Iteration:  1323   Dual objective     =       1922843.031041
Iteration:  1764   Dual objective     =       1998906.362167
Iteration:  2205   Dual objective     =       2065001.342547
Iteration:  2646   Dual objective     =       2122614.557377
Iteration:  3087   Dual objective     =       2169234.439272
Iteration:  3528   Dual objective     =       2204160.986010
Iteration:  3969   Dual objective     =       2230034.669281
Iteration:  4410   Dual objective     =       2245570.002792

Dual simplex solved model.

solution for: inventory_optimization
objective: 2.25047e+06
status: OPTIMAL_SOLUTION(2)
x_W9_PRD-JWX7=27.000
x_W2_PRD-GOE7=37.000
x_W5_PRD-OIF8=33.000
x_W4_PRD-F1FA=24.000
x_W10_PRD-2M47=26.000
x_W7_PRD-01CA=36.000
x_W6_PRD-C4J9=37.000
x_W1_PRD-5ZM0=27.000
x_W1_PRD-IMWN=25.000
x_W10_PRD-EE85=27.000
x_W1_PRD-95VZ=25.000
x_W3_PRD-WGLN=33.000
x_W9_PRD-BS3S=36.000
x_W1_PRD-EN1E=29.000
x_W8_PRD-2KSM=38.000
x_W1_PRD-LJ7V=32.000
x_W5_PRD-5USE=25.000
x_W4_PRD-E2A1=26.000
x_W7_PRD-J3YR=37.000
x_W2_PRD-QQE7=36.000
x_W3_PRD-11ML=37.000
x_W9_PRD-YMP4=27.000
x_W2_PRD-FD2N=26.000
x_W1_PRD-Q8XG=37.000
x_W2_PRD-V9GN=37.000
x_W3_PRD-03HG=20.000
x_W1_PRD-JLFI=27.000
x_W7_PRD-5NPE=36.000
x_W1_PRD-NSSO=25.000
x_W8_PRD-HTKL=32.000
x_W10_PRD-VMHD=38.000
x_W2_PRD-N52Z=28.000
x_W8_PRD-YGPF=35.000
x_W9_PRD-P6M2=38.000
x_W8_PRD-01K8=38.000
x_W9_PRD-X5OM=26.000
x_W3_PRD-9AEJ=24.000
x_W6_PRD-P27K=38.000
x_W1_PRD-UV33=25.000
x_W3_PRD-YQE1=12.000
x_W10_PRD-IGQ3=36.000
x_W10_PRD-QLV2=27.000
x_W10_PRD-REXQ=19.000
x_W1_PRD-CPUS=25.000
x_W8_PRD-CGQA=26.000
x_W10_PRD-GP81=36.000
x_W10_PRD-RDGG=36.000
x_W8_PRD-W4XQ=37.000
x_W8_PRD-H864=36.000
x_W10_PRD-SJ44=36.000
x_W10_PRD-I71X=25.000
x_W9_PRD-SWLU=36.000
x_W1_PRD-MB4V=27.000
x_W2_PRD-UGGR=20.000
x_W7_PRD-JOBO=38.000
x_W1_PRD-8VA6=26.000
x_W9_PRD-88O8=36.000
x_W5_PRD-RBZC=16.000
x_W7_PRD-GBSP=14.000
x_W8_PRD-8DWP=38.000
x_W8_PRD-XG9D=37.000
x_W3_PRD-SQ1L=36.000
x_W8_PRD-EFRT=29.000
x_W2_PRD-JW4D=26.000
x_W8_PRD-XMOM=28.000
x_W5_PRD-QUK5=26.000
x_W4_PRD-L7DC=27.000
x_W4_PRD-8MHY=26.000
x_W10_PRD-IBZX=36.000
x_W2_PRD-QQ3W=26.000
x_W4_PRD-DR0W=25.000
x_W9_PRD-LJG8=18.000
x_W6_PRD-1BT7=38.000
x_W4_PRD-46DW=38.000
x_W9_PRD-A95K=12.000
x_W3_PRD-9L5W=36.000
x_W4_PRD-UMAQ=22.000
x_W9_PRD-Z3KD=13.000
x_W7_PRD-2WCF=11.000
x_W10_PRD-TXUD=37.000
x_W10_PRD-F5OV=14.000
x_W2_PRD-G0ED=37.000
x_W7_PRD-KNT1=36.000
x_W8_PRD-2JGJ=38.000
x_W5_PRD-1I88=30.000
x_W1_PRD-FUQC=38.000
x_W1_PRD-L3D3=25.000
x_W8_PRD-RRYG=27.000
x_W3_PRD-KS2A=13.000
x_W3_PRD-K54G=33.000
x_W1_PRD-5DNE=25.000
x_W9_PRD-EIO7=38.000
x_W5_PRD-XZ9N=25.000
x_W1_PRD-NNI1=34.000
x_W6_PRD-1D0D=25.000
x_W5_PRD-JNSO=23.000
x_W6_PRD-LHJ7=12.000
x_W5_PRD-DSBQ=14.000
x_W10_PRD-AMF1=38.000
x_W4_PRD-M1KS=36.000
x_W8_PRD-0BVX=12.000
x_W4_PRD-CVPH=36.000
x_W8_PRD-ZLMT=36.000
x_W3_PRD-HV59=21.000
x_W8_PRD-5TMQ=26.000
x_W4_PRD-K1U7=38.000
x_W4_PRD-10W9=36.000
x_W4_PRD-1M4I=27.000
x_W8_PRD-B8TD=34.000
x_W1_PRD-0QZG=29.000
x_W8_PRD-ANLX=23.000
x_W4_PRD-QG5R=26.000
x_W8_PRD-DXBC=26.000
x_W9_PRD-12MH=8.000
x_W3_PRD-MSR4=19.000
x_W2_PRD-JQKK=9.000
x_W8_PRD-A1VN=20.000
x_W3_PRD-2JMJ=36.000
x_W6_PRD-N35G=37.000
x_W7_PRD-05LT=25.000
x_W8_PRD-7B9N=37.000
x_W1_PRD-2T13=30.000
x_W3_PRD-XIEM=33.000
x_W4_PRD-QYBJ=31.000
x_W1_PRD-IALI=19.000
x_W4_PRD-SGFF=28.000
x_W6_PRD-OZQU=26.000
x_W3_PRD-CYF5=25.000
x_W9_PRD-F2WL=25.000
x_W9_PRD-8IAV=13.000
x_W5_PRD-IDRF=10.000
x_W7_PRD-LCF9=31.000
x_W2_PRD-EZSE=37.000
x_W7_PRD-28VI=25.000
x_W8_PRD-1057=24.000
x_W7_PRD-6R9A=27.000
x_W2_PRD-YXKE=24.000
x_W8_PRD-G8P0=19.000
x_W7_PRD-ILIU=36.000
x_W5_PRD-CVVD=39.000
x_W8_PRD-5YM4=37.000
x_W10_PRD-LIFF=38.000
x_W6_PRD-15EJ=39.000
x_W9_PRD-REGW=36.000
x_W10_PRD-0UPP=25.000
x_W4_PRD-UBU1=36.000
x_W8_PRD-A6TO=12.000
x_W3_PRD-A103=17.000
x_W7_PRD-7IJ4=32.000
x_W5_PRD-3YPH=12.000
x_W3_PRD-TQST=26.000
x_W9_PRD-Y4NA=32.000
x_W8_PRD-3PXL=25.000
x_W2_PRD-RGMK=30.000
x_W5_PRD-I56I=27.000
x_W2_PRD-57Z2=38.000
x_W2_PRD-NO1B=13.000
x_W10_PRD-54CU=28.000
x_W10_PRD-3GWD=12.000
x_W3_PRD-U0H1=25.000
x_W9_PRD-8YLC=8.000
x_W9_PRD-05QB=25.000
x_W10_PRD-YRX8=18.000
x_W3_PRD-G0NF=27.000
x_W5_PRD-Y797=18.000
x_W9_PRD-V4KC=28.000
x_W3_PRD-QO6M=12.000
x_W6_PRD-7FMM=36.000
x_W6_PRD-RZO9=25.000
x_W9_PRD-QZD4=27.000
x_W4_PRD-8FC0=32.000
x_W2_PRD-KYU4=36.000
x_W7_PRD-0M2R=23.000
x_W1_PRD-7Y7E=39.000
x_W7_PRD-R7XB=12.000
x_W1_PRD-9IHY=24.000
x_W6_PRD-QM9H=38.000
x_W9_PRD-T0A2=29.000
x_W10_PRD-3WQC=37.000
x_W1_PRD-FJPO=12.000
x_W7_PRD-QLK4=26.000
x_W4_PRD-CJY0=36.000
x_W3_PRD-6BIQ=39.000
x_W4_PRD-P4Y6=38.000
x_W10_PRD-7XQ5=29.000
x_W3_PRD-7SS3=19.000
x_W3_PRD-73K1=24.000
x_W1_PRD-EZIZ=17.000
x_W3_PRD-HOH9=27.000
x_W2_PRD-L9JX=36.000
x_W10_PRD-FYG8=35.000
x_W2_PRD-53W3=8.000
x_W5_PRD-9IT8=25.000
x_W4_PRD-KZP1=36.000
x_W1_PRD-KAII=25.000
x_W10_PRD-FEYP=17.000
x_W7_PRD-CWBF=39.000
x_W2_PRD-T7ZP=8.000
x_W1_PRD-VF0O=26.000
x_W9_PRD-T86P=15.000
x_W1_PRD-3KDK=26.000
x_W2_PRD-A0EF=10.000
x_W10_PRD-UGT7=37.000
x_W3_PRD-CF14=26.000
x_W8_PRD-E6IO=38.000
x_W8_PRD-ZNOS=26.000
x_W2_PRD-SZLP=13.000
x_W10_PRD-7TYO=38.000
x_W6_PRD-6R9Q=10.000
x_W9_PRD-DYFM=14.000
x_W7_PRD-946X=19.000
x_W5_PRD-TCI1=27.000
x_W10_PRD-LJEW=14.000
x_W6_PRD-3QXX=16.000
x_W6_PRD-67W1=37.000
x_W1_PRD-UD11=14.000
x_W4_PRD-DEDQ=37.000
x_W7_PRD-LLI1=9.000
x_W9_PRD-YXK4=38.000
x_W1_PRD-8YQH=20.000
x_W9_PRD-IU3Q=15.000
x_W8_PRD-VKC2=36.000
x_W5_PRD-1HWC=38.000
x_W4_PRD-62SD=8.000
x_W1_PRD-R30H=9.000
x_W8_PRD-MEWJ=13.000
x_W8_PRD-X3RW=26.000
x_W2_PRD-U8JQ=27.000
x_W2_PRD-J3MD=12.000
x_W7_PRD-RMR9=26.000
x_W2_PRD-SD3M=14.000
x_W2_PRD-4ZNE=37.000
x_W10_PRD-L2NR=25.000
x_W5_PRD-33MY=37.000
x_W8_PRD-T2W4=19.000
x_W6_PRD-YM70=12.000
x_W6_PRD-CIIU=37.000
x_W7_PRD-DEGS=27.000
x_W9_PRD-E1IO=26.000
x_W7_PRD-3DFH=26.000
x_W9_PRD-AUYO=10.000
x_W10_PRD-I0CH=27.000
x_W3_PRD-TZTF=12.000
x_W4_PRD-0OT2=26.000
x_W9_PRD-88A1=19.000
x_W2_PRD-8Z6H=12.000
x_W9_PRD-FBF5=10.000
x_W4_PRD-922R=27.000
x_W5_PRD-RAM7=25.000
x_W2_PRD-M6C0=16.000
x_W4_PRD-IAB5=17.000
x_W5_PRD-FNWV=25.000
x_W4_PRD-2ZQY=17.000
x_W10_PRD-WMHF=23.000
x_W8_PRD-FH4O=10.000
x_W8_PRD-JFQ9=26.000
x_W5_PRD-SJQJ=13.000
x_W4_PRD-GYBZ=38.000
x_W4_PRD-ZV9F=26.000
x_W7_PRD-06B8=25.000
x_W3_PRD-FL1K=18.000
x_W10_PRD-ONZE=24.000
x_W3_PRD-P3KT=36.000
x_W7_PRD-R9L2=24.000
x_W7_PRD-V6JR=19.000
x_W5_PRD-MOT4=31.000
x_W9_PRD-T6BA=25.000
x_W5_PRD-8U17=9.000
x_W6_PRD-3TTA=18.000
x_W3_PRD-QKHE=38.000
x_W2_PRD-ZD0X=17.000
x_W6_PRD-71G8=14.000
x_W1_PRD-D1Y0=25.000
x_W2_PRD-78JZ=10.000
x_W10_PRD-FXT0=13.000
x_W2_PRD-QJMA=19.000
x_W4_PRD-P1F9=13.000
x_W1_PRD-640N=12.000
x_W8_PRD-61OZ=38.000
x_W7_PRD-CT4U=25.000
x_W4_PRD-1XP0=9.000
x_W8_PRD-EVPY=28.000
x_W8_PRD-4XQF=27.000
x_W6_PRD-K88X=37.000
x_W9_PRD-VU92=25.000
x_W1_PRD-EWHK=13.000
x_W3_PRD-BX8N=27.000
x_W5_PRD-PHV9=9.000
x_W6_PRD-M53I=37.000
x_W7_PRD-PGOB=18.000
x_W1_PRD-F4GO=38.000
x_W2_PRD-TJ00=37.000
x_W2_PRD-AOAU=38.000
x_W3_PRD-6UMO=37.000
x_W1_PRD-PNUL=19.000
x_W8_PRD-77KK=26.000
x_W8_PRD-LM4M=20.000
x_W8_PRD-FF6P=37.000
x_W10_PRD-NCFO=17.000
x_W8_PRD-68BT=14.000
x_W10_PRD-QHHX=37.000
x_W10_PRD-SY2B=10.000
x_W1_PRD-MJ90=36.000
x_W7_PRD-CQ1H=18.000
x_W2_PRD-9S2L=18.000
x_W8_PRD-CRIH=30.000
x_W7_PRD-3GB2=26.000
x_W5_PRD-BSBZ=25.000
x_W4_PRD-C5JA=36.000
x_W10_PRD-R02C=12.000
x_W7_PRD-SBIH=26.000
x_W10_PRD-7HO8=8.000
x_W4_PRD-GCTE=31.000
x_W1_PRD-HFKF=36.000
x_W7_PRD-5YUL=9.000
x_W6_PRD-1JZX=18.000
x_W4_PRD-GODT=18.000
x_W4_PRD-HAH9=14.000
x_W7_PRD-O3O0=26.000
x_W1_PRD-ILGS=12.000
x_W8_PRD-QT6N=14.000
x_W9_PRD-SNNP=18.000
x_W9_PRD-G7KY=8.000
x_W8_PRD-0SQN=15.000
x_W3_PRD-08HX=37.000
x_W3_PRD-RMS2=36.000
x_W5_PRD-NWB1=26.000
x_W9_PRD-6TM4=36.000
x_W3_PRD-XGCS=19.000
x_W9_PRD-P8G0=26.000
x_W5_PRD-DQGZ=32.000
x_W2_PRD-VKFG=14.000
x_W6_PRD-BJ4U=13.000
x_W9_PRD-1AN7=19.000
x_W7_PRD-XS8D=28.000
x_W5_PRD-AZ3O=37.000
x_W1_PRD-V4CW=16.000
x_W3_PRD-7WTW=38.000
x_W6_PRD-051D=37.000
x_W10_PRD-WWKO=17.000
x_W9_PRD-5NII=38.000
x_W8_PRD-T7BX=36.000
x_W2_PRD-HLDG=21.000
x_W10_PRD-BO4G=18.000
x_W8_PRD-VT52=18.000
x_W8_PRD-EFCX=10.000
x_W9_PRD-0W4M=8.000
x_W9_PRD-4URH=13.000
x_W1_PRD-6ZV8=18.000
x_W2_PRD-R5SX=36.000
x_W1_PRD-WCLX=14.000
x_W6_PRD-17YP=38.000
x_W9_PRD-EF6K=15.000
x_W8_PRD-OXOY=37.000
x_W5_PRD-FSUB=27.000
x_W4_PRD-WHNF=25.000
x_W5_PRD-4U3X=10.000
x_W8_PRD-XXB4=14.000
x_W8_PRD-RTFE=25.000
x_W4_PRD-AL7J=25.000
x_W2_PRD-D0Z1=28.000
x_W5_PRD-09WD=18.000
x_W9_PRD-NF9U=36.000
x_W6_PRD-Q4M3=27.000
x_W9_PRD-BVRM=17.000
x_W7_PRD-XCJL=38.000
x_W2_PRD-M99N=18.000
x_W6_PRD-6B8H=13.000
x_W7_PRD-N76E=17.000
x_W6_PRD-Y38Z=37.000
x_W2_PRD-8YQ7=28.000
x_W5_PRD-8PTB=28.000
x_W6_PRD-F0OR=38.000
x_W10_PRD-FOEK=9.000
x_W9_PRD-HF9T=17.000
x_W9_PRD-AWZK=14.000
x_W9_PRD-MUX7=15.000
x_W2_PRD-0AJ4=37.000
x_W2_PRD-NHO6=24.000
x_W3_PRD-12U0=14.000
x_W3_PRD-T36C=36.000
x_W3_PRD-TN24=10.000
x_W3_PRD-8Z4P=37.000
x_W1_PRD-WSN8=27.000
x_W1_PRD-78UY=31.000
x_W6_PRD-YYOW=31.000
x_W10_PRD-1TSZ=26.000
x_W8_PRD-32KH=8.000
x_W8_PRD-PJXU=20.000
x_W10_PRD-WLBK=36.000
x_W6_PRD-67E9=16.000
x_W7_PRD-W3IO=13.000
x_W5_PRD-8R44=27.000
x_W3_PRD-ZHVM=28.000
x_W5_PRD-K3I4=20.000
x_W2_PRD-3ACT=13.000
x_W4_PRD-ORIE=14.000
x_W8_PRD-QQ5Z=38.000
x_W8_PRD-F3TA=38.000
x_W10_PRD-M2GA=27.000
x_W4_PRD-6W21=13.000
x_W9_PRD-AD37=26.000
x_W5_PRD-C4S5=28.000
x_W6_PRD-VA5J=29.000
x_W10_PRD-O7FE=14.000
x_W9_PRD-39MH=37.000
x_W10_PRD-YUV1=17.000
x_W2_PRD-L7D4=9.000
x_W7_PRD-1NXN=18.000
x_W8_PRD-OICR=25.000
x_W5_PRD-ICIW=36.000
x_W7_PRD-0J86=12.000
x_W7_PRD-MUI5=33.000
x_W9_PRD-AZ1K=38.000
x_W7_PRD-PL4T=27.000
x_W8_PRD-TM7P=28.000
x_W8_PRD-T5G6=18.000
x_W10_PRD-9KWJ=23.000
x_W6_PRD-ZIY9=28.000
x_W1_PRD-ONB4=14.000
x_W7_PRD-V1JK=31.000
x_W7_PRD-A5QF=10.000
x_W10_PRD-4CTN=38.000
x_W6_PRD-7CPQ=27.000
x_W10_PRD-3BJY=12.000
x_W8_PRD-A6V0=18.000
x_W2_PRD-TKAZ=8.000
x_W4_PRD-NJYP=18.000
x_W1_PRD-L9CF=9.000
x_W10_PRD-JQOI=13.000
x_W8_PRD-ESDT=30.000
x_W4_PRD-NWKL=39.000
x_W10_PRD-4YHJ=17.000
x_W3_PRD-Z7Z5=39.000
x_W8_PRD-2RFI=9.000
x_W5_PRD-Z8KJ=10.000
x_W9_PRD-D8H0=14.000
x_W8_PRD-CL68=26.000
x_W5_PRD-SCE8=12.000
x_W8_PRD-7Q0M=25.000
x_W9_PRD-EC8V=27.000
x_W4_PRD-K6V1=38.000
x_W2_PRD-88G0=26.000
x_W4_PRD-1XCK=12.000
x_W8_PRD-Z2ZX=14.000
x_W3_PRD-CJGS=24.000
x_W6_PRD-LPIH=23.000
x_W8_PRD-XUSP=38.000
x_W4_PRD-NX5D=18.000
x_W10_PRD-804B=27.000
x_W1_PRD-AAD1=12.000
x_W10_PRD-BACD=26.000
x_W4_PRD-1ZKC=37.000
x_W10_PRD-XYYN=13.000
x_W4_PRD-B9UM=20.000
x_W2_PRD-2OXK=12.000
x_W5_PRD-XE8M=25.000
x_W6_PRD-OVL1=28.000
x_W10_PRD-L1GH=25.000
x_W1_PRD-0DV9=27.000
x_W1_PRD-QB1G=9.000
x_W5_PRD-S4AP=18.000
x_W6_PRD-NPDW=29.000
x_W3_PRD-G36W=37.000
x_W5_PRD-VF5Y=32.000
x_W3_PRD-S32R=10.000
x_W1_PRD-ALZU=29.000
x_W6_PRD-JEIX=14.000
x_W7_PRD-835S=25.000
x_W10_PRD-LTPI=24.000
x_W9_PRD-G9RP=20.000
x_W5_PRD-6BJD=36.000
x_W7_PRD-EK3H=25.000
x_W6_PRD-4R6V=27.000
x_W6_PRD-BM1I=19.000
x_W3_PRD-AJLX=14.000
x_W3_PRD-9F3Z=13.000
x_W10_PRD-0PG8=10.000
x_W7_PRD-GRPR=19.000
x_W10_PRD-9Z3G=36.000
x_W2_PRD-R867=37.000
x_W9_PRD-SLBH=18.000
x_W9_PRD-DOEK=38.000
x_W4_PRD-DREI=30.000
x_W3_PRD-0095=15.000
x_W6_PRD-U7F4=14.000
x_W8_PRD-KWWQ=15.000
x_W7_PRD-TXQM=36.000
x_W10_PRD-BTPB=38.000
x_W4_PRD-EPY9=11.000
x_W2_PRD-0ULN=33.000
x_W9_PRD-O924=13.000
x_W4_PRD-9TRL=27.000
x_W6_PRD-OCJ4=10.000
x_W10_PRD-SU3D=13.000
x_W9_PRD-1X12=17.000
x_W9_PRD-R0SO=36.000
x_W3_PRD-0QWN=27.000
x_W1_PRD-4EU6=9.000
x_W6_PRD-83XB=19.000
x_W2_PRD-XI1I=32.000
x_W8_PRD-K5WF=14.000
x_W7_PRD-Q90K=9.000
x_W1_PRD-UQ97=17.000
x_W6_PRD-6C03=38.000
x_W2_PRD-KZ79=13.000
x_W10_PRD-5YSJ=21.000
x_W2_PRD-2ZSM=20.000
x_W2_PRD-K18T=11.000
x_W2_PRD-PQMR=18.000
x_W9_PRD-4GES=17.000
x_W9_PRD-9VE8=33.000
x_W5_PRD-LGHJ=37.000
x_W6_PRD-PWID=8.000
x_W8_PRD-8L7Y=18.000
x_W5_PRD-P0SU=14.000
x_W3_PRD-NWPS=17.000
x_W8_PRD-HW4X=17.000
x_W3_PRD-UDBL=18.000
x_W8_PRD-2ECQ=26.000
x_W4_PRD-7I19=36.000
x_W7_PRD-LOZ3=18.000
x_W4_PRD-YK79=27.000
x_W7_PRD-OA8F=37.000
x_W9_PRD-915P=13.000
x_W1_PRD-EOSH=14.000
x_W7_PRD-G9W2=13.000
x_W2_PRD-DRMB=24.000
x_W4_PRD-2O6S=27.000
x_W10_PRD-8CN1=14.000
x_W10_PRD-25YI=36.000
x_W9_PRD-47Y0=36.000
x_W10_PRD-KXG8=13.000
x_W10_PRD-BL9K=14.000
x_W5_PRD-O4GO=24.000
x_W5_PRD-CQTL=27.000
x_W2_PRD-SEFV=13.000
x_W3_PRD-Q5UD=27.000
x_W7_PRD-55GK=12.000
x_W8_PRD-57SX=14.000
x_W2_PRD-3HKN=26.000
x_W4_PRD-VL3B=14.000
x_W5_PRD-4TQL=19.000
x_W1_PRD-GJZW=8.000
x_W9_PRD-1JFL=16.000
x_W5_PRD-SM2H=12.000
x_W5_PRD-2RM2=20.000
x_W4_PRD-SLWO=29.000
x_W2_PRD-2B3N=37.000
x_W2_PRD-USUO=31.000
x_W4_PRD-LH4G=36.000
x_W7_PRD-JNVG=37.000
x_W7_PRD-4L7G=25.000
x_W5_PRD-4J8S=19.000
x_W1_PRD-TW4H=12.000
x_W5_PRD-56G5=36.000
x_W2_PRD-EI3G=25.000
x_W1_PRD-JA9W=27.000
x_W6_PRD-2931=26.000
x_W3_PRD-3U1F=8.000
x_W9_PRD-56SB=9.000
x_W7_PRD-ZYD5=8.000
x_W7_PRD-BQW5=26.000
x_W4_PRD-U048=18.000
x_W5_PRD-196J=27.000
x_W1_PRD-NTWR=27.000
x_W3_PRD-JN2G=16.000
x_W2_PRD-CLBW=10.000
x_W8_PRD-EOUP=25.000
x_W6_PRD-Q7W0=18.000
x_W5_PRD-8JGG=39.000
x_W3_PRD-8ZVV=38.000
x_W7_PRD-9BK3=14.000
x_W10_PRD-M5J7=18.000
x_W2_PRD-KR3E=38.000
x_W9_PRD-YXK0=36.000
x_W1_PRD-9HAT=8.000
x_W10_PRD-UE57=9.000
x_W6_PRD-52GA=19.000
x_W10_PRD-X1PQ=18.000
x_W10_PRD-KON5=12.000
x_W2_PRD-R4D1=8.000
x_W7_PRD-YX1B=25.000
x_W2_PRD-U98C=15.000
x_W1_PRD-HRNL=11.000
x_W7_PRD-FWHD=36.000
x_W7_PRD-RIFE=38.000
x_W4_PRD-FWFX=38.000
x_W4_PRD-4UY5=38.000
x_W7_PRD-ACCG=26.000
x_W4_PRD-6UVZ=9.000
x_W4_PRD-4O79=18.000
x_W6_PRD-BMP8=17.000
x_W10_PRD-3EZG=18.000
x_W8_PRD-TMRU=8.000
x_W3_PRD-IHI9=38.000
x_W6_PRD-A5AO=18.000
x_W7_PRD-4MU6=9.000
x_W10_PRD-1V28=16.000
x_W3_PRD-6I1J=37.000
x_W1_PRD-X4RU=17.000
x_W8_PRD-TXVP=26.000
x_W9_PRD-N7YZ=32.000
x_W7_PRD-IWDN=37.000
x_W4_PRD-YZLT=23.000
x_W2_PRD-L3G2=39.000
x_W9_PRD-LEQO=26.000
x_W1_PRD-G04Q=25.000
x_W2_PRD-JIJG=37.000
x_W1_PRD-M5ZU=9.000
x_W4_PRD-4ZPJ=28.000
x_W7_PRD-MNUY=36.000
x_W1_PRD-JGRY=20.000
x_W5_PRD-1SX3=14.000
x_W2_PRD-95K9=27.000
x_W10_PRD-GZ87=17.000
x_W4_PRD-Z2AB=28.000
x_W8_PRD-VA1W=22.000
x_W9_PRD-22PF=24.000
x_W8_PRD-AL7Z=8.000
x_W6_PRD-PYSF=25.000
x_W5_PRD-VFQ0=26.000
x_W9_PRD-9AIJ=12.000
x_W8_PRD-E7L7=24.000
x_W3_PRD-V4E4=27.000
x_W9_PRD-P60Q=18.000
x_W9_PRD-0H1H=9.000
x_W2_PRD-6BK9=11.000
x_W2_PRD-VGL7=13.000
x_W1_PRD-YNVK=12.000
x_W9_PRD-9ONT=20.000
x_W3_PRD-052T=13.000
x_W4_PRD-8QT1=38.000
x_W10_PRD-C2BV=26.000
x_W1_PRD-ZWHA=28.000
x_W8_PRD-C3QL=9.000
x_W10_PRD-6UAO=18.000
x_W9_PRD-S7VQ=19.000
x_W7_PRD-166X=37.000
x_W1_PRD-WMY4=23.000
x_W8_PRD-COF5=18.000
x_W4_PRD-2XM7=30.000
x_W3_PRD-FIWA=25.000
x_W10_PRD-BWAZ=27.000
x_W1_PRD-RDS1=16.000
x_W5_PRD-9U18=12.000
x_W3_PRD-M3QX=38.000
x_W4_PRD-6SAY=36.000
x_W2_PRD-0ARI=33.000
x_W8_PRD-36DH=13.000
x_W2_PRD-EST2=19.000
x_W9_PRD-OIYT=20.000
x_W7_PRD-H2AK=36.000
x_W1_PRD-UIU3=36.000
x_W4_PRD-312R=14.000
x_W1_PRD-KW43=28.000
x_W6_PRD-HUUW=21.000
x_W4_PRD-SJW1=25.000
x_W2_PRD-XP2Y=20.000
x_W1_PRD-GCJN=38.000
x_W2_PRD-2H0G=14.000
x_W3_PRD-BNSG=27.000
x_W9_PRD-58JE=17.000
x_W5_PRD-OMLB=30.000
x_W9_PRD-DFLT=12.000
x_W4_PRD-2NZT=24.000
x_W8_PRD-EKD7=12.000
x_W8_PRD-C830=36.000
x_W1_PRD-W3NA=14.000
x_W4_PRD-4Q81=26.000
x_W3_PRD-PTYU=30.000
x_W4_PRD-MGGQ=10.000
x_W7_PRD-XIVN=38.000
x_W2_PRD-9PEL=25.000
x_W2_PRD-BOAK=36.000
x_W9_PRD-IDHJ=23.000
x_W6_PRD-32B5=19.000
x_W1_PRD-WV7L=18.000
x_W5_PRD-1I2X=19.000
x_W2_PRD-9V3S=19.000
x_W3_PRD-PHOB=32.000
x_W1_PRD-8HML=22.000
x_W8_PRD-IWRW=8.000
x_W7_PRD-L6PS=8.000
x_W6_PRD-H62G=38.000
x_W4_PRD-O22V=23.000
x_W4_PRD-65L5=17.000
x_W3_PRD-D74A=24.000
x_W3_PRD-MR4C=14.000
x_W1_PRD-7KXN=25.000
x_W5_PRD-L7NZ=10.000
x_W5_PRD-KZNM=35.000
x_W3_PRD-OWZR=35.000
x_W4_PRD-MN3Y=37.000
x_W4_PRD-X6KU=37.000
x_W1_PRD-NO91=25.000
x_W5_PRD-32W7=10.000
x_W8_PRD-324U=18.000
x_W8_PRD-1UQN=25.000
x_W4_PRD-OTAC=36.000
x_W4_PRD-U7M0=18.000
x_W1_PRD-Y9EC=27.000
x_W7_PRD-X41P=36.000
x_W4_PRD-4EI2=26.000
x_W4_PRD-8NS5=13.000
x_W2_PRD-8JVA=9.000
x_W1_PRD-YB0R=19.000
x_W6_PRD-L50P=23.000
x_W4_PRD-SWCF=25.000
x_W6_PRD-U6WV=27.000
x_W5_PRD-O1EM=36.000
x_W4_PRD-E7CJ=10.000
x_W4_PRD-2356=9.000
x_W1_PRD-G4SW=29.000
x_W1_PRD-O3W1=29.000
x_W8_PRD-BGF3=19.000
x_W3_PRD-GNVC=11.000
x_W3_PRD-QMQB=8.000
x_W2_PRD-V6QG=26.000
x_W4_PRD-KV2Q=18.000
x_W1_PRD-BHT3=38.000
x_W7_PRD-CYZ2=27.000
x_W6_PRD-FRU0=12.000
x_W8_PRD-KUUV=27.000
x_W2_PRD-I993=16.000
x_W1_PRD-QL50=17.000
x_W6_PRD-GM8F=16.000
x_W2_PRD-BIQV=12.000
x_W4_PRD-VK4B=27.000
x_W4_PRD-4IVV=30.000
x_W7_PRD-G7N8=22.000
x_W9_PRD-G504=19.000
x_W9_PRD-3903=14.000
x_W6_PRD-QNTT=26.000
x_W4_PRD-MK6D=38.000
x_W8_PRD-8E0Q=23.000
x_W4_PRD-VGY5=36.000
x_W4_PRD-EX40=26.000
x_W8_PRD-FTPP=12.000
x_W1_PRD-YHBH=36.000
x_W10_PRD-B0JA=10.000
x_W7_PRD-JX3K=13.000
x_W9_PRD-M9IF=27.000
x_W10_PRD-S897=23.000
x_W4_PRD-4UGH=12.000
x_W8_PRD-KE7T=12.000
x_W8_PRD-8BSQ=29.000
x_W10_PRD-EGIR=17.000
x_W4_PRD-TXZP=27.000
x_W9_PRD-DVQ4=32.000
x_W3_PRD-E042=26.000
x_W1_PRD-1BJR=10.000
x_W3_PRD-5FDD=38.000
x_W5_PRD-UXGW=19.000
x_W5_PRD-TGCH=17.000
x_W3_PRD-FIL2=37.000
x_W8_PRD-ZE94=24.000
x_W3_PRD-77GL=28.000
x_W8_PRD-F7C6=38.000
x_W1_PRD-TEKU=38.000
x_W2_PRD-LTPC=26.000
x_W4_PRD-QA7C=14.000
x_W4_PRD-0PX8=13.000
x_W1_PRD-JFBA=9.000
x_W3_PRD-JNYV=25.000
x_W9_PRD-F2NL=20.000
x_W10_PRD-R6R5=15.000
x_W5_PRD-TKNJ=19.000
x_W6_PRD-OF6L=36.000
x_W10_PRD-DYGH=26.000
x_W4_PRD-9CCM=13.000
x_W4_PRD-RFE8=24.000
x_W10_PRD-QCGQ=12.000
x_W3_PRD-PZTS=19.000
x_W9_PRD-R52B=31.000
x_W1_PRD-R5V6=14.000
x_W4_PRD-A0HW=18.000
x_W9_PRD-LMVH=36.000
x_W6_PRD-F393=19.000
x_W9_PRD-OFFQ=24.000
x_W5_PRD-LOEF=19.000
x_W6_PRD-Q637=18.000
x_W8_PRD-HXW8=19.000
x_W4_PRD-CJ7G=20.000
x_W10_PRD-3LO6=18.000
x_W5_PRD-E2GT=22.000
x_W3_PRD-OFEP=13.000
x_W6_PRD-00C5=18.000
x_W6_PRD-HVMJ=25.000
x_W8_PRD-OAA6=26.000
x_W8_PRD-FB2O=27.000
x_W9_PRD-0M8C=27.000
x_W5_PRD-7725=38.000
x_W4_PRD-17EL=12.000
x_W2_PRD-UN5N=20.000
x_W1_PRD-UO4G=25.000
x_W9_PRD-RK7N=30.000
x_W8_PRD-WI76=24.000
x_W10_PRD-JP1H=37.000
x_W1_PRD-FA7T=30.000
x_W5_PRD-NJHO=19.000
x_W10_PRD-YQHL=8.000
x_W4_PRD-D9DI=30.000
x_W2_PRD-M4KX=36.000
x_W3_PRD-DGZE=25.000
x_W3_PRD-7O58=18.000
x_W1_PRD-UDAF=10.000
x_W2_PRD-ONA5=8.000
x_W7_PRD-RY31=13.000
x_W7_PRD-U63U=37.000
x_W5_PRD-F6VJ=21.000
x_W10_PRD-EFVL=13.000
x_W10_PRD-J3BE=18.000
x_W7_PRD-BM4V=14.000
x_W7_PRD-PYF4=37.000
x_W7_PRD-IK8A=23.000
x_W4_PRD-6JET=24.000
x_W10_PRD-XH9A=23.000
x_W2_PRD-6XDU=8.000
x_W3_PRD-WVOW=14.000
x_W3_PRD-2P7I=28.000
x_W3_PRD-ONSA=12.000
x_W1_PRD-TJYJ=32.000
x_W3_PRD-55Z1=9.000
x_W9_PRD-RWV7=38.000
x_W8_PRD-KLE3=9.000
x_W7_PRD-6Z4G=18.000
x_W1_PRD-I4XW=18.000
x_W6_PRD-SAOK=25.000
x_W1_PRD-J591=9.000
x_W5_PRD-PK20=18.000
x_W8_PRD-UV3D=14.000
x_W2_PRD-JJWI=19.000
x_W4_PRD-6F1M=9.000
x_W9_PRD-9WIH=35.000
x_W6_PRD-B1E9=36.000
x_W2_PRD-00KD=13.000
x_W2_PRD-VOLQ=26.000
x_W2_PRD-IK24=25.000
x_W6_PRD-LKUL=27.000
x_W1_PRD-E8K5=19.000
x_W4_PRD-2UC7=25.000
x_W1_PRD-2UWY=13.000
x_W6_PRD-3516=14.000
x_W3_PRD-TL7Q=13.000
x_W3_PRD-99AR=8.000
x_W8_PRD-EYPC=12.000
x_W2_PRD-IQM6=14.000
x_W1_PRD-2UN0=20.000
x_W8_PRD-T72F=19.000
x_W5_PRD-PLO7=28.000
x_W5_PRD-5YG6=9.000
x_W9_PRD-0FS2=16.000
x_W3_PRD-J6T9=27.000
x_W10_PRD-LPUN=13.000
x_W1_PRD-UU8O=19.000
x_W4_PRD-XDG9=18.000
x_W6_PRD-MBXJ=16.000
x_W3_PRD-BPDK=19.000
x_W2_PRD-V6MA=25.000
x_W4_PRD-DM86=17.000
x_W10_PRD-4LT3=18.000
x_W4_PRD-T6EP=29.000
x_W4_PRD-EUSD=26.000
x_W2_PRD-RYOM=19.000
x_W4_PRD-9I6J=18.000
x_W2_PRD-XP9X=12.000
x_W2_PRD-X3R7=36.000
x_W10_PRD-DR8J=21.000
x_W5_PRD-SWDJ=17.000
x_W1_PRD-7BCZ=26.000
x_W2_PRD-CHCJ=16.000
x_W2_PRD-6387=23.000
x_W5_PRD-EJ97=18.000
x_W4_PRD-GRWF=14.000
x_W1_PRD-JENM=27.000
x_W8_PRD-0C2K=18.000
x_W3_PRD-0PAG=18.000
x_W5_PRD-VRW2=9.000
x_W1_PRD-VJF2=18.000
x_W5_PRD-KDDL=15.000
x_W8_PRD-WVL9=19.000
x_W10_PRD-ANS7=36.000
x_W8_PRD-58CX=13.000
x_W3_PRD-JG80=9.000
x_W4_PRD-7ZGX=26.000
x_W9_PRD-HYMK=19.000
x_W2_PRD-IPAA=25.000
x_W8_PRD-BS0H=18.000
x_W2_PRD-HQS4=15.000
x_W1_PRD-KC2U=12.000

In [92]:
results = []

for (warehouse_id, product_id), var in x.items():

    qty = var.solution_value

    if qty is not None and qty > 0:

        # Warehouse information
        wh = warehouse_opt_df[
            (warehouse_opt_df['warehouse_id'] == warehouse_id)
            &
            (warehouse_opt_df['product_id'] == product_id)
        ].iloc[0]

        # Forecast / reorder information
        reorder_info = reorder_df[
            reorder_df['product_id'] == product_id
        ].iloc[0]

        # Product information
        product_info = warehouse_df[
            warehouse_df['product_id'] == product_id
        ].iloc[0]

        results.append({

            # Warehouse fields
            'warehouse_id': warehouse_id,

            'warehouse_location':
                wh['warehouse_location'],

            # Product fields
            'product_id': product_id,

            'product_name':
                product_info['product_name'],

            'category':
                product_info['category'],

            'sub_category':
                product_info['sub_category'],

            'brand':
                product_info['brand'],

            # Optimization output
            'shipment_quantity':
                round(qty, 2),

            'warehouse_available_stock':
                wh['available_stock'],

            'distance_to_store':
                wh['distance_to_store'],

            'lead_time_days':
                wh['lead_time_days'],

            # Forecast fields
            'predicted_demand':
                reorder_info['predicted_demand'],

            'reorder_quantity':
                reorder_info['reorder_quantity']

        })

In [93]:
optimized_replenishment_df = pd.DataFrame(results)

optimized_replenishment_df = (

    optimized_replenishment_df

    .sort_values(
        by=['product_id', 'shipment_quantity'],
        ascending=[True, False]
    )

)

In [94]:
optimized_replenishment_df = (
    optimized_replenishment_df
    .reset_index(drop=True)
)
optimized_replenishment_df.head(50)

,warehouse_id,warehouse_location,product_id,product_name,category,sub_category,brand,shipment_quantity,warehouse_available_stock,distance_to_store,lead_time_days,predicted_demand,reorder_quantity
0,W10,Hempstead,PRD-0009,Bedsheet Set Cotton,Home,Furniture,Fitbit,8.0,6711,25,3,2.68,8.0
1,W8,Yonkers,PRD-001I,LED Strip Lights 5m,Home,Appliances,Philips,4.0,2815,80,12,2.61,4.0
2,W6,New Rochelle,PRD-006F,USB Hub 7-Port,Electronics,Laptops,Xiaomi,7.0,203,50,11,1.37,7.0
3,W3,Syracruse,PRD-0075,Portable SSD 1TB,Electronics,Laptops,Philips,17.0,3221,155,10,5.31,17.0
4,W3,Syracruse,PRD-0095,Treadmill Folding,Sports,Gym Equipment,Philips,15.0,2500,155,6,1.69,15.0
5,W7,Schenectady,PRD-00AN,Sports Bra High Impact,Clothing,Womens Wear,Anker,20.0,6218,300,4,5.42,20.0
6,W6,New Rochelle,PRD-00C5,USB-C Fast Charger 65W,Electronics,Audio,HP,18.0,201,50,9,2.68,18.0
7,W8,Yonkers,PRD-00HJ,Digital Blood Pressure Monitor,Health,Fitness,Nikon,5.0,2814,80,12,2.69,5.0
8,W2,Buffalo,PRD-00KD,Screen Protector Tempered Glass,Electronics,Smartphones,Xiaomi,13.0,6926,280,5,1.94,13.0
9,W8,Yonkers,PRD-00KN,Portable SSD 1TB,Electronics,Tablets,HP,24.0,2811,80,12,4.98,24.0
10,W1,Rochester,PRD-00OY,Digital Thermometer,Health,Personal Care,Huawei,11.0,3216,150,5,3.77,11.0
11,W10,Hempstead,PRD-00PD,4K Webcam Pro,Electronics,Cameras,Nike,1.0,6713,25,14,1.93,1.0
12,W3,Syracruse,PRD-00QS,Desk Lamp LED,Home,Kitchen,JBL,27.0,3211,155,12,5.38,27.0
13,W8,Yonkers,PRD-00V2,Yoga Mat Non-Slip,Health,Supplements,Canon,1.0,2827,80,2,3.86,1.0
14,W3,Syracruse,PRD-00Z2,USB Hub 7-Port,Electronics,Tablets,Asus,13.0,3213,155,4,3.66,13.0
15,W7,Schenectady,PRD-0118,Jump Rope Speed,Sports,Outdoor,Fitbit,1.0,6218,300,6,2.70,1.0
16,W4,Albany,PRD-015Q,Digital Blood Pressure Monitor,Health,Fitness,Anker,11.0,3227,200,7,5.33,11.0
17,W7,Schenectady,PRD-01CA,Desk Lamp LED,Home,Bedding,Sony,36.0,6202,300,8,5.42,36.0
18,W7,Schenectady,PRD-01FL,Gym Gloves,Sports,Accessories,Xiaomi,16.0,6203,300,4,2.71,16.0
19,W8,Yonkers,PRD-01K8,Coffee Maker Automatic,Home,Bedding,Asus,38.0,900,80,14,5.34,38.0
20,W5,Utica,PRD-01KD,Casual Sneakers,Clothing,Womens Wear,HP,18.0,3207,180,12,3.54,18.0
21,W3,Syracruse,PRD-01RD,Portable SSD 1TB,Electronics,Tablets,Huawei,3.0,3217,155,10,1.89,3.0
22,W7,Schenectady,PRD-01U5,Swimming Goggles,Sports,Gym Equipment,Apple,27.0,6211,300,11,5.42,27.0
23,W10,Hempstead,PRD-024X,Running Shoes Air Zoom,Clothing,Mens Wear,Fitbit,20.0,1914,25,1,5.00,20.0
24,W10,Hempstead,PRD-029D,Badminton Racket,Sports,Gym Equipment,Logitech,17.0,6721,25,9,5.35,17.0
25,W3,Syracruse,PRD-02AD,Coffee Maker Automatic,Home,Decor,Adidas,2.0,3236,155,1,5.36,2.0
26,W5,Utica,PRD-02CS,Smart Watch Series 8,Electronics,Cameras,Samsung,14.0,3224,180,12,5.36,14.0
27,W8,Yonkers,PRD-02RI,Treadmill Folding,Sports,Gym Equipment,Samsung,3.0,2824,80,3,3.77,3.0
28,W4,Albany,PRD-02T2,Running Shoes Air Zoom,Clothing,Accessories,Samsung,10.0,3228,200,4,5.38,10.0
29,W2,Buffalo,PRD-0326,Storage Box Set,Home,Decor,Baseus,10.0,7206,280,7,2.17,10.0
30,W2,Buffalo,PRD-036Z,Yoga Pants Leggings,Clothing,Shoes,HP,19.0,7201,280,13,2.72,19.0
31,W6,New Rochelle,PRD-037X,Blender 1000W,Home,Kitchen,Samsung,4.0,10934,50,3,2.67,4.0
32,W9,Mount Vernon,PRD-038X,Cotton T-Shirt Pack,Clothing,Accessories,Nike,29.0,4206,240,6,4.95,29.0
33,W4,Albany,PRD-03E7,Bedsheet Set Cotton,Home,Kitchen,Nike,6.0,7745,200,6,2.54,6.0
34,W8,Yonkers,PRD-03GB,Foam Roller,Health,Fitness,Nikon,20.0,2807,80,3,3.78,20.0
35,W8,Yonkers,PRD-03GC,Winter Jacket Waterproof,Clothing,Womens Wear,Adidas,29.0,2809,80,4,5.32,29.0
36,W3,Syracruse,PRD-03HG,USB-C Fast Charger 65W,Electronics,Cameras,Samsung,20.0,2500,155,3,1.84,20.0
37,W3,Syracruse,PRD-03KX,Baseball Cap,Clothing,Womens Wear,Sony,5.0,7671,155,1,2.49,5.0
38,W9,Mount Vernon,PRD-03MI,Bedsheet Set Cotton,Home,Kitchen,Baseus,6.0,10957,240,1,1.36,6.0
39,W8,Yonkers,PRD-03V2,Exercise Ball,Sports,Sports Wear,Lenovo,12.0,2826,80,1,5.32,12.0
40,W2,Buffalo,PRD-03YS,Bedsheet Set Cotton,Home,Furniture,Sony,25.0,7213,280,2,5.34,25.0
41,W9,Mount Vernon,PRD-03ZE,Treadmill Folding,Sports,Outdoor,HP,20.0,4213,240,1,4.19,20.0
42,W3,Syracruse,PRD-043J,Fitness Smart Band,Health,Fitness,Apple,26.0,3201,155,3,3.77,26.0
43,W7,Schenectady,PRD-04EQ,Bedsheet Set Cotton,Home,Kitchen,Fitbit,5.0,6217,300,6,3.01,5.0
44,W2,Buffalo,PRD-04PM,Power Bank 20000mAh,Electronics,Accessories,Lenovo,9.0,7218,280,7,3.80,9.0
45,W3,Syracruse,PRD-04S9,Portable SSD 1TB,Electronics,Smartphones,Adidas,16.0,7868,155,2,2.65,16.0
46,W2,Buffalo,PRD-04WT,Bedsheet Set Cotton,Home,Appliances,Canon,4.0,7210,280,3,1.87,4.0
47,W6,New Rochelle,PRD-051D,Casual Sneakers,Clothing,Accessories,JBL,37.0,201,50,9,5.35,37.0
48,W8,Yonkers,PRD-0520,Power Bank 20000mAh,Electronics,Smartphones,Logitech,13.0,4763,80,7,2.35,13.0
49,W3,Syracruse,PRD-052T,Massage Gun Deep Tissue,Health,Medical Devices,Baseus,13.0,3201,155,11,1.90,13.0

In [95]:
optimized_replenishment_df.to_csv(
    'optimized_replenishment_plan.csv',
    index=False
)

print("Optimization complete.")

Optimization complete.

In [96]:
len(optimized_replenishment_df)

11535